package com.bosch.rts.entity;

// Generated Nov 14, 2011 9:29:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InterviewHistory generated by hbm2java.
 */
@Entity
@Table(name = "trts_interview_history")
public class InterviewHistory implements java.io.Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = -4173058788654405092L;
	
	/** The ith interview history id. */
	private Integer ithInterviewHistoryId;
	
	/** The recruit request. */
	private RecruitRequest recruitRequest;
	
	/** The candidate. */
	private Candidate candidate;
	
	/** The ith status. */
	private String ithStatus;
	
	/** The ith update date. */
	private Date ithUpdateDate;
	
	/** The ith request number. */
	private Integer ithRequestNumber;

	/**
	 * Instantiates a new interview history.
	 */
	public InterviewHistory() {
	}

	/**
	 * Instantiates a new interview history.
	 *
	 * @param recruitRequest the recruit request
	 * @param candidate the candidate
	 * @param ithStatus the ith status
	 * @param ithUpdateDate the ith update date
	 * @param requestNumber the request number
	 */
	public InterviewHistory(RecruitRequest recruitRequest, Candidate candidate,
			String ithStatus, Date ithUpdateDate, Integer requestNumber) {
		this.recruitRequest = recruitRequest;
		this.candidate = candidate;
		this.ithStatus = ithStatus;
		this.ithUpdateDate = ithUpdateDate;
		this.ithRequestNumber = requestNumber;
	}

	/**
	 * Gets the ith interview history id.
	 *
	 * @return the ith interview history id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ith_interview_history_id", unique = true, nullable = false)
	public Integer getIthInterviewHistoryId() {
		return this.ithInterviewHistoryId;
	}

	/**
	 * Sets the ith interview history id.
	 *
	 * @param ithInterviewHistoryId the new ith interview history id
	 */
	public void setIthInterviewHistoryId(Integer ithInterviewHistoryId) {
		this.ithInterviewHistoryId = ithInterviewHistoryId;
	}

	/**
	 * Gets the ith request number.
	 *
	 * @return the ith request number
	 */
	@Column(name = "ith_request_number")
	public Integer getIthRequestNumber() {
		return ithRequestNumber;
	}

	/**
	 * Sets the ith request number.
	 *
	 * @param ithRequestNumber the new ith request number
	 */
	public void setIthRequestNumber(Integer ithRequestNumber) {
		this.ithRequestNumber = ithRequestNumber;
	}

	/**
	 * Gets the recruit request.
	 *
	 * @return the recruit request
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ith_rcr_recruit_request_id")
	public RecruitRequest getRecruitRequest() {
		return this.recruitRequest;
	}

	/**
	 * Sets the recruit request.
	 *
	 * @param recruitRequest the new recruit request
	 */
	public void setRecruitRequest(RecruitRequest recruitRequest) {
		this.recruitRequest = recruitRequest;
	}

	/**
	 * Gets the candidate.
	 *
	 * @return the candidate
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ith_cdd_candidate_id")
	public Candidate getCandidate() {
		return this.candidate;
	}

	/**
	 * Sets the candidate.
	 *
	 * @param candidate the new candidate
	 */
	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	/**
	 * Gets the ith status.
	 *
	 * @return the ith status
	 */
	@Column(name = "ith_status", length = 25)
	public String getIthStatus() {
		return this.ithStatus;
	}

	/**
	 * Sets the ith status.
	 *
	 * @param ithStatus the new ith status
	 */
	public void setIthStatus(String ithStatus) {
		this.ithStatus = ithStatus;
	}

	/**
	 * Gets the ith update date.
	 *
	 * @return the ith update date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ith_update_date", length = 19)
	public Date getIthUpdateDate() {
		return this.ithUpdateDate;
	}

	/**
	 * Sets the ith update date.
	 *
	 * @param ithUpdateDate the new ith update date
	 */
	public void setIthUpdateDate(Date ithUpdateDate) {
		this.ithUpdateDate = ithUpdateDate;
	}

}
