package com.bosch.rts.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RecruitRequestHasSkill generated by hbm2java.
 */
@Entity
@Table(name = "trts_recruit_request_has_skill")
public class RecruitRequestHasSkill implements java.io.Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1563767553442428204L;
	
	/** The rhs recruit request skill id. */
	private Integer rhsRecruitRequestSkillId;
	
	/** The skill. */
	private Skill skill;
	
	/** The recruit request. */
	private RecruitRequest recruitRequest;
	
	/** The rhs required experience years from. */
	private Integer rhsRequiredExperienceYearsFrom;
	
	/** The rhs required experience years to. */
	private Integer rhsRequiredExperienceYearsTo;
	
	/** The skill level. */
	private String skillLevel;

	/**
	 * Instantiates a new recruit request has skill.
	 */
	public RecruitRequestHasSkill() {
	}

	/**
	 * Instantiates a new recruit request has skill.
	 *
	 * @param skill the skill
	 * @param recruitRequest the recruit request
	 * @param rhsRequiredExperienceYearsFrom the rhs required experience years from
	 * @param rhsRequiredExperienceYearsTo the rhs required experience years to
	 * @param skillLevel the skill level
	 */
	public RecruitRequestHasSkill(Skill skill, RecruitRequest recruitRequest,
			Integer rhsRequiredExperienceYearsFrom,
			Integer rhsRequiredExperienceYearsTo, String skillLevel) {
		this.skill = skill;
		this.recruitRequest = recruitRequest;
		this.rhsRequiredExperienceYearsFrom = rhsRequiredExperienceYearsFrom;
		this.rhsRequiredExperienceYearsTo = rhsRequiredExperienceYearsTo;
		this.skillLevel = skillLevel;
	}

	/**
	 * Gets the rhs recruit request skill id.
	 *
	 * @return the rhs recruit request skill id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rhs_recruit_request_skill_id", unique = true, nullable = false)
	public Integer getRhsRecruitRequestSkillId() {
		return this.rhsRecruitRequestSkillId;
	}

	/**
	 * Sets the rhs recruit request skill id.
	 *
	 * @param rhsRecruitRequestSkillId the new rhs recruit request skill id
	 */
	public void setRhsRecruitRequestSkillId(Integer rhsRecruitRequestSkillId) {
		this.rhsRecruitRequestSkillId = rhsRecruitRequestSkillId;
	}

	/**
	 * Gets the skill.
	 *
	 * @return the skill
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rhs_skil_skill_id")
	public Skill getSkill() {
		return this.skill;
	}

	/**
	 * Sets the skill.
	 *
	 * @param skill the new skill
	 */
	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	/**
	 * Gets the recruit request.
	 *
	 * @return the recruit request
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rhs_rcr_recruit_request_id")
	public RecruitRequest getRecruitRequest() {
		return this.recruitRequest;
	}

	/**
	 * Sets the recruit request.
	 *
	 * @param recruitRequest the new recruit request
	 */
	public void setRecruitRequest(RecruitRequest recruitRequest) {
		this.recruitRequest = recruitRequest;
	}

	/**
	 * Gets the rhs required experience years from.
	 *
	 * @return the rhs required experience years from
	 */
	@Column(name = "rhs_required_experience_years_from")
	public Integer getRhsRequiredExperienceYearsFrom() {
		return this.rhsRequiredExperienceYearsFrom;
	}

	/**
	 * Sets the rhs required experience years from.
	 *
	 * @param rhsRequiredExperienceYearsFrom the new rhs required experience years from
	 */
	public void setRhsRequiredExperienceYearsFrom(
			Integer rhsRequiredExperienceYearsFrom) {
		this.rhsRequiredExperienceYearsFrom = rhsRequiredExperienceYearsFrom;
	}

	/**
	 * Gets the rhs required experience years to.
	 *
	 * @return the rhs required experience years to
	 */
	@Column(name = "rhs_required_experience_years_to")
	public Integer getRhsRequiredExperienceYearsTo() {
		return this.rhsRequiredExperienceYearsTo;
	}

	/**
	 * Sets the rhs required experience years to.
	 *
	 * @param rhsRequiredExperienceYearsTo the new rhs required experience years to
	 */
	public void setRhsRequiredExperienceYearsTo(
			Integer rhsRequiredExperienceYearsTo) {
		this.rhsRequiredExperienceYearsTo = rhsRequiredExperienceYearsTo;
	}
	
	/**
	 * Gets the skill level.
	 *
	 * @return the skill level
	 */
	@Column(name = "rhs_skill_level", nullable = true)
	public String getSkillLevel() {
		return this.skillLevel;
	}
	
	/**
	 * Sets the skill level.
	 *
	 * @param skillLevel the new skill level
	 */
	public void setSkillLevel(String skillLevel) {
		this.skillLevel = skillLevel;
	}

}