package com.bosch.rts.entity;

// Generated Jun 5, 2013 10:58:58 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TechnicalResultAttributeValue generated by hbm2java.
 */
@Entity
@Table(name = "trts_technical_result_attribute_value", 
		uniqueConstraints = { @UniqueConstraint( columnNames = { "attribute_id", "interview_schedule_id" } ) } )
public class TechnicalResultAttributeValue implements java.io.Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1833216195510006728L;
	
	/** The id. */
	private int id;	
	
	/** The attribute id. */
	private int attributeId;	
	
	/** The value. */
	private String value;
	
	/** The created on. */
	private Date createdOn;
	
	/** The created by. */
	private String createdBy;
	
	/** The updated on. */
	private Date updatedOn;
	
	/** The updated by. */
	private String updatedBy;
	
	/** The interview schedule id. */
	private int interviewScheduleId;	

	/**
	 * Instantiates a new technical result attribute value.
	 */
	public TechnicalResultAttributeValue() {
	}

	/**
	 * Instantiates a new technical result attribute value.
	 *
	 * @param id the id
	 * @param value the value
	 * @param createdOn the created on
	 * @param createdBy the created by
	 */
	public TechnicalResultAttributeValue(int id,
			String value, Date createdOn, String createdBy) {
		this.id = id;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	/**
	 * Instantiates a new technical result attribute value.
	 *
	 * @param id the id
	 * @param interviewScheduleId the interview schedule id
	 * @param attributeId the attribute id
	 * @param value the value
	 * @param createdOn the created on
	 * @param createdBy the created by
	 * @param updatedOn the updated on
	 * @param updatedBy the updated by
	 */
	public TechnicalResultAttributeValue(int id, int interviewScheduleId,
			int attributeId, String value,
			Date createdOn, String createdBy, Date updatedOn, String updatedBy) {
		this.id = id;
		this.interviewScheduleId = interviewScheduleId;
		this.attributeId = attributeId;
		this.value = value;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
	}
	
	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}
	
	/**
	 * Gets the value.
	 *
	 * @return the value
	 */
	@Column(name = "value", nullable = true, length = 200)
	@Length(max = 200)
	public String getValue() {
		return this.value;
	}

	/**
	 * Sets the value.
	 *
	 * @param value the new value
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the created on.
	 *
	 * @return the created on
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", nullable = false, length = 0)
	@NotNull
	public Date getCreatedOn() {
		return this.createdOn;
	}

	/**
	 * Sets the created on.
	 *
	 * @param createdOn the new created on
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "created_by", nullable = false, length = 12)
	@NotNull
	@Length(max = 12)
	public String getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Gets the updated on.
	 *
	 * @return the updated on
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "updated_on", length = 0)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	/**
	 * Sets the updated on.
	 *
	 * @param updatedOn the new updated on
	 */
	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	/**
	 * Gets the updated by.
	 *
	 * @return the updated by
	 */
	@Column(name = "updated_by", length = 12)
	@Length(max = 12)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	/**
	 * Sets the updated by.
	 *
	 * @param updatedBy the new updated by
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}
	
	/**
	 * Sets the interview schedule id.
	 *
	 * @param interviewScheduleId the new interview schedule id
	 */
	public void setInterviewScheduleId(int interviewScheduleId) {
		this.interviewScheduleId = interviewScheduleId;
	}

	/**
	 * Gets the interview schedule id.
	 *
	 * @return the interview schedule id
	 */
	@Column(name = "interview_schedule_id")
	public int getInterviewScheduleId() {
		return interviewScheduleId;
	}

	/**
	 * Sets the attribute id.
	 *
	 * @param attributeId the new attribute id
	 */
	public void setAttributeId(int attributeId) {
		this.attributeId = attributeId;
	}

	/**
	 * Gets the attribute id.
	 *
	 * @return the attribute id
	 */
	@Column(name = "attribute_id")
	public int getAttributeId() {
		return attributeId;
	}

}
