package model;
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Figurelink generated by hbm2java
 */
public class Figurelink implements java.io.Serializable {

	private Integer figureId;
	private String figureDesc;
	private String figurePath;
	private Set<Questionfigure> questionfigures = new HashSet<Questionfigure>(0);
	private Set<Questionitemfigure> questionitemfigures = new HashSet<Questionitemfigure>(
			0);

	public Figurelink() {
	}

	public Figurelink(String figurePath) {
		this.figurePath = figurePath;
	}

	public Figurelink(String figureDesc, String figurePath,
			Set<Questionfigure> questionfigures,
			Set<Questionitemfigure> questionitemfigures) {
		this.figureDesc = figureDesc;
		this.figurePath = figurePath;
		this.questionfigures = questionfigures;
		this.questionitemfigures = questionitemfigures;
	}

	public Integer getFigureId() {
		return this.figureId;
	}

	public void setFigureId(Integer figureId) {
		this.figureId = figureId;
	}

	public String getFigureDesc() {
		return this.figureDesc;
	}

	public void setFigureDesc(String figureDesc) {
		this.figureDesc = figureDesc;
	}

	public String getFigurePath() {
		return this.figurePath;
	}

	public void setFigurePath(String figurePath) {
		this.figurePath = figurePath;
	}

	public Set<Questionfigure> getQuestionfigures() {
		return this.questionfigures;
	}

	public void setQuestionfigures(Set<Questionfigure> questionfigures) {
		this.questionfigures = questionfigures;
	}

	public Set<Questionitemfigure> getQuestionitemfigures() {
		return this.questionitemfigures;
	}

	public void setQuestionitemfigures(
			Set<Questionitemfigure> questionitemfigures) {
		this.questionitemfigures = questionitemfigures;
	}

}
