package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Questionitem generated by hbm2java
 */
public class Questionitem implements java.io.Serializable {

	private Integer questItemId;
	private Question question;
	private String questItemFace;
	private String questItemValue;
	private Set<Questionsolution> questionsolutionsForPreviousQuestItemId = new HashSet<Questionsolution>(
			0);
	private Set<Questionsolution> questionsolutionsForQuestItemId = new HashSet<Questionsolution>(
			0);
	private Set<Questionsolution> questionsolutionsForNextQuestItemId = new HashSet<Questionsolution>(
			0);
	private Set<Questionitemfigure> questionitemfigures = new HashSet<Questionitemfigure>(
			0);
	private Set<Questioniteminfo> questioniteminfos = new HashSet<Questioniteminfo>(
			0);

	public Questionitem() {
	}

	public Questionitem(Question question, String questItemFace,
			String questItemValue,
			Set<Questionsolution> questionsolutionsForPreviousQuestItemId,
			Set<Questionsolution> questionsolutionsForQuestItemId,
			Set<Questionsolution> questionsolutionsForNextQuestItemId,
			Set<Questionitemfigure> questionitemfigures,
			Set<Questioniteminfo> questioniteminfos) {
		this.question = question;
		this.questItemFace = questItemFace;
		this.questItemValue = questItemValue;
		this.questionsolutionsForPreviousQuestItemId = questionsolutionsForPreviousQuestItemId;
		this.questionsolutionsForQuestItemId = questionsolutionsForQuestItemId;
		this.questionsolutionsForNextQuestItemId = questionsolutionsForNextQuestItemId;
		this.questionitemfigures = questionitemfigures;
		this.questioniteminfos = questioniteminfos;
	}

	public Integer getQuestItemId() {
		return this.questItemId;
	}

	public void setQuestItemId(Integer questItemId) {
		this.questItemId = questItemId;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public String getQuestItemFace() {
		return this.questItemFace;
	}

	public void setQuestItemFace(String questItemFace) {
		this.questItemFace = questItemFace;
	}

	public String getQuestItemValue() {
		return this.questItemValue;
	}

	public void setQuestItemValue(String questItemValue) {
		this.questItemValue = questItemValue;
	}

	public Set<Questionsolution> getQuestionsolutionsForPreviousQuestItemId() {
		return this.questionsolutionsForPreviousQuestItemId;
	}

	public void setQuestionsolutionsForPreviousQuestItemId(
			Set<Questionsolution> questionsolutionsForPreviousQuestItemId) {
		this.questionsolutionsForPreviousQuestItemId = questionsolutionsForPreviousQuestItemId;
	}

	public Set<Questionsolution> getQuestionsolutionsForQuestItemId() {
		return this.questionsolutionsForQuestItemId;
	}

	public void setQuestionsolutionsForQuestItemId(
			Set<Questionsolution> questionsolutionsForQuestItemId) {
		this.questionsolutionsForQuestItemId = questionsolutionsForQuestItemId;
	}

	public Set<Questionsolution> getQuestionsolutionsForNextQuestItemId() {
		return this.questionsolutionsForNextQuestItemId;
	}

	public void setQuestionsolutionsForNextQuestItemId(
			Set<Questionsolution> questionsolutionsForNextQuestItemId) {
		this.questionsolutionsForNextQuestItemId = questionsolutionsForNextQuestItemId;
	}

	public Set<Questionitemfigure> getQuestionitemfigures() {
		return this.questionitemfigures;
	}

	public void setQuestionitemfigures(
			Set<Questionitemfigure> questionitemfigures) {
		this.questionitemfigures = questionitemfigures;
	}

	public Set<Questioniteminfo> getQuestioniteminfos() {
		return this.questioniteminfos;
	}

	public void setQuestioniteminfos(Set<Questioniteminfo> questioniteminfos) {
		this.questioniteminfos = questioniteminfos;
	}

}
