package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Questiontopic generated by hbm2java
 */
public class Questiontopic implements java.io.Serializable {

	private Integer questTopicId;
	private Question question;
	private Topic topic;
	private Character questTopicLevel;

	public Questiontopic() {
	}

	public Questiontopic(Question question, Topic topic,
			Character questTopicLevel) {
		this.question = question;
		this.topic = topic;
		this.questTopicLevel = questTopicLevel;
	}

	public Integer getQuestTopicId() {
		return this.questTopicId;
	}

	public void setQuestTopicId(Integer questTopicId) {
		this.questTopicId = questTopicId;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	public Character getQuestTopicLevel() {
		return this.questTopicLevel;
	}

	public void setQuestTopicLevel(Character questTopicLevel) {
		this.questTopicLevel = questTopicLevel;
	}

}
