package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Questionfigure generated by hbm2java
 */
public class Questionfigure implements java.io.Serializable {

	private Integer questFigId;
	private Question question;
	private Figurelink figurelink;
	private String questFigDesc;

	public Questionfigure() {
	}

	public Questionfigure(Question question, Figurelink figurelink,
			String questFigDesc) {
		this.question = question;
		this.figurelink = figurelink;
		this.questFigDesc = questFigDesc;
	}

	public Integer getQuestFigId() {
		return this.questFigId;
	}

	public void setQuestFigId(Integer questFigId) {
		this.questFigId = questFigId;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public Figurelink getFigurelink() {
		return this.figurelink;
	}

	public void setFigurelink(Figurelink figurelink) {
		this.figurelink = figurelink;
	}

	public String getQuestFigDesc() {
		return this.questFigDesc;
	}

	public void setQuestFigDesc(String questFigDesc) {
		this.questFigDesc = questFigDesc;
	}

}
