package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Questionsolution generated by hbm2java
 */
public class Questionsolution implements java.io.Serializable {

	private Integer questSolId;
	private Question question;
	private Questionitem questionitemByPreviousQuestItemId;
	private Questionitem questionitemByNextQuestItemId;
	private Questionitem questionitemByQuestItemId;
	private Byte questSolOrder;

	public Questionsolution() {
	}

	public Questionsolution(Question question,
			Questionitem questionitemByPreviousQuestItemId,
			Questionitem questionitemByNextQuestItemId,
			Questionitem questionitemByQuestItemId, Byte questSolOrder) {
		this.question = question;
		this.questionitemByPreviousQuestItemId = questionitemByPreviousQuestItemId;
		this.questionitemByNextQuestItemId = questionitemByNextQuestItemId;
		this.questionitemByQuestItemId = questionitemByQuestItemId;
		this.questSolOrder = questSolOrder;
	}

	public Integer getQuestSolId() {
		return this.questSolId;
	}

	public void setQuestSolId(Integer questSolId) {
		this.questSolId = questSolId;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public Questionitem getQuestionitemByPreviousQuestItemId() {
		return this.questionitemByPreviousQuestItemId;
	}

	public void setQuestionitemByPreviousQuestItemId(
			Questionitem questionitemByPreviousQuestItemId) {
		this.questionitemByPreviousQuestItemId = questionitemByPreviousQuestItemId;
	}

	public Questionitem getQuestionitemByNextQuestItemId() {
		return this.questionitemByNextQuestItemId;
	}

	public void setQuestionitemByNextQuestItemId(
			Questionitem questionitemByNextQuestItemId) {
		this.questionitemByNextQuestItemId = questionitemByNextQuestItemId;
	}

	public Questionitem getQuestionitemByQuestItemId() {
		return this.questionitemByQuestItemId;
	}

	public void setQuestionitemByQuestItemId(
			Questionitem questionitemByQuestItemId) {
		this.questionitemByQuestItemId = questionitemByQuestItemId;
	}

	public Byte getQuestSolOrder() {
		return this.questSolOrder;
	}

	public void setQuestSolOrder(Byte questSolOrder) {
		this.questSolOrder = questSolOrder;
	}

}
