package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Questionitemfigure generated by hbm2java
 */
public class Questionitemfigure implements java.io.Serializable {

	private Integer itemFigId;
	private Questionitem questionitem;
	private Figurelink figurelink;
	private String itemFigDesc;

	public Questionitemfigure() {
	}

	public Questionitemfigure(Questionitem questionitem, Figurelink figurelink,
			String itemFigDesc) {
		this.questionitem = questionitem;
		this.figurelink = figurelink;
		this.itemFigDesc = itemFigDesc;
	}

	public Integer getItemFigId() {
		return this.itemFigId;
	}

	public void setItemFigId(Integer itemFigId) {
		this.itemFigId = itemFigId;
	}

	public Questionitem getQuestionitem() {
		return this.questionitem;
	}

	public void setQuestionitem(Questionitem questionitem) {
		this.questionitem = questionitem;
	}

	public Figurelink getFigurelink() {
		return this.figurelink;
	}

	public void setFigurelink(Figurelink figurelink) {
		this.figurelink = figurelink;
	}

	public String getItemFigDesc() {
		return this.itemFigDesc;
	}

	public void setItemFigDesc(String itemFigDesc) {
		this.itemFigDesc = itemFigDesc;
	}

}
