package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Questioniteminfo generated by hbm2java
 */
public class Questioniteminfo implements java.io.Serializable {

	private Integer itemInfoId;
	private Questionitem questionitem;
	private String itemInfoProp;
	private String itemInfoValue;

	public Questioniteminfo() {
	}

	public Questioniteminfo(String itemInfoProp, String itemInfoValue) {
		this.itemInfoProp = itemInfoProp;
		this.itemInfoValue = itemInfoValue;
	}

	public Questioniteminfo(Questionitem questionitem, String itemInfoProp,
			String itemInfoValue) {
		this.questionitem = questionitem;
		this.itemInfoProp = itemInfoProp;
		this.itemInfoValue = itemInfoValue;
	}

	public Integer getItemInfoId() {
		return this.itemInfoId;
	}

	public void setItemInfoId(Integer itemInfoId) {
		this.itemInfoId = itemInfoId;
	}

	public Questionitem getQuestionitem() {
		return this.questionitem;
	}

	public void setQuestionitem(Questionitem questionitem) {
		this.questionitem = questionitem;
	}

	public String getItemInfoProp() {
		return this.itemInfoProp;
	}

	public void setItemInfoProp(String itemInfoProp) {
		this.itemInfoProp = itemInfoProp;
	}

	public String getItemInfoValue() {
		return this.itemInfoValue;
	}

	public void setItemInfoValue(String itemInfoValue) {
		this.itemInfoValue = itemInfoValue;
	}

}
