package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Questioninfo generated by hbm2java
 */
public class Questioninfo implements java.io.Serializable {

	private Integer questInfoId;
	private Question question;
	private String questInfoProp;
	private String questInfoValue;

	public Questioninfo() {
	}

	public Questioninfo(String questInfoProp, String questInfoValue) {
		this.questInfoProp = questInfoProp;
		this.questInfoValue = questInfoValue;
	}

	public Questioninfo(Question question, String questInfoProp,
			String questInfoValue) {
		this.question = question;
		this.questInfoProp = questInfoProp;
		this.questInfoValue = questInfoValue;
	}

	public Integer getQuestInfoId() {
		return this.questInfoId;
	}

	public void setQuestInfoId(Integer questInfoId) {
		this.questInfoId = questInfoId;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public String getQuestInfoProp() {
		return this.questInfoProp;
	}

	public void setQuestInfoProp(String questInfoProp) {
		this.questInfoProp = questInfoProp;
	}

	public String getQuestInfoValue() {
		return this.questInfoValue;
	}

	public void setQuestInfoValue(String questInfoValue) {
		this.questInfoValue = questInfoValue;
	}

}
