package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Sharedquestion generated by hbm2java
 */
public class Sharedquestion implements java.io.Serializable {

	private Integer sharedQuestId;
	private Lecturer lecturerBySharerId;
	private Question question;
	private Lecturer lecturerByShareeId;
	private boolean sharedQuestViewable;
	private boolean sharedQuestModifiable;
	private boolean sharedQuestResharable;

	public Sharedquestion() {
	}

	public Sharedquestion(boolean sharedQuestViewable,
			boolean sharedQuestModifiable, boolean sharedQuestResharable) {
		this.sharedQuestViewable = sharedQuestViewable;
		this.sharedQuestModifiable = sharedQuestModifiable;
		this.sharedQuestResharable = sharedQuestResharable;
	}

	public Sharedquestion(Lecturer lecturerBySharerId, Question question,
			Lecturer lecturerByShareeId, boolean sharedQuestViewable,
			boolean sharedQuestModifiable, boolean sharedQuestResharable) {
		this.lecturerBySharerId = lecturerBySharerId;
		this.question = question;
		this.lecturerByShareeId = lecturerByShareeId;
		this.sharedQuestViewable = sharedQuestViewable;
		this.sharedQuestModifiable = sharedQuestModifiable;
		this.sharedQuestResharable = sharedQuestResharable;
	}

	public Integer getSharedQuestId() {
		return this.sharedQuestId;
	}

	public void setSharedQuestId(Integer sharedQuestId) {
		this.sharedQuestId = sharedQuestId;
	}

	public Lecturer getLecturerBySharerId() {
		return this.lecturerBySharerId;
	}

	public void setLecturerBySharerId(Lecturer lecturerBySharerId) {
		this.lecturerBySharerId = lecturerBySharerId;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public Lecturer getLecturerByShareeId() {
		return this.lecturerByShareeId;
	}

	public void setLecturerByShareeId(Lecturer lecturerByShareeId) {
		this.lecturerByShareeId = lecturerByShareeId;
	}

	public boolean isSharedQuestViewable() {
		return this.sharedQuestViewable;
	}

	public void setSharedQuestViewable(boolean sharedQuestViewable) {
		this.sharedQuestViewable = sharedQuestViewable;
	}

	public boolean isSharedQuestModifiable() {
		return this.sharedQuestModifiable;
	}

	public void setSharedQuestModifiable(boolean sharedQuestModifiable) {
		this.sharedQuestModifiable = sharedQuestModifiable;
	}

	public boolean isSharedQuestResharable() {
		return this.sharedQuestResharable;
	}

	public void setSharedQuestResharable(boolean sharedQuestResharable) {
		this.sharedQuestResharable = sharedQuestResharable;
	}

}
