package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Squestionsolution generated by hbm2java
 */
public class Squestionsolution implements java.io.Serializable {

	private Integer squestSolId;
	private Tquestionitem tquestionitemByTquestNextItemId;
	private Tquestionitem tquestionitemByTquestPreviousItemId;
	private Studentsolution studentsolution;
	private Tquestionitem tquestionitemByTquestItemId;
	private Byte squestSolOrder;
	private String squestSolComment;

	public Squestionsolution() {
	}

	public Squestionsolution(Tquestionitem tquestionitemByTquestNextItemId,
			Tquestionitem tquestionitemByTquestPreviousItemId,
			Studentsolution studentsolution,
			Tquestionitem tquestionitemByTquestItemId, Byte squestSolOrder,
			String squestSolComment) {
		this.tquestionitemByTquestNextItemId = tquestionitemByTquestNextItemId;
		this.tquestionitemByTquestPreviousItemId = tquestionitemByTquestPreviousItemId;
		this.studentsolution = studentsolution;
		this.tquestionitemByTquestItemId = tquestionitemByTquestItemId;
		this.squestSolOrder = squestSolOrder;
		this.squestSolComment = squestSolComment;
	}

	public Integer getSquestSolId() {
		return this.squestSolId;
	}

	public void setSquestSolId(Integer squestSolId) {
		this.squestSolId = squestSolId;
	}

	public Tquestionitem getTquestionitemByTquestNextItemId() {
		return this.tquestionitemByTquestNextItemId;
	}

	public void setTquestionitemByTquestNextItemId(
			Tquestionitem tquestionitemByTquestNextItemId) {
		this.tquestionitemByTquestNextItemId = tquestionitemByTquestNextItemId;
	}

	public Tquestionitem getTquestionitemByTquestPreviousItemId() {
		return this.tquestionitemByTquestPreviousItemId;
	}

	public void setTquestionitemByTquestPreviousItemId(
			Tquestionitem tquestionitemByTquestPreviousItemId) {
		this.tquestionitemByTquestPreviousItemId = tquestionitemByTquestPreviousItemId;
	}

	public Studentsolution getStudentsolution() {
		return this.studentsolution;
	}

	public void setStudentsolution(Studentsolution studentsolution) {
		this.studentsolution = studentsolution;
	}

	public Tquestionitem getTquestionitemByTquestItemId() {
		return this.tquestionitemByTquestItemId;
	}

	public void setTquestionitemByTquestItemId(
			Tquestionitem tquestionitemByTquestItemId) {
		this.tquestionitemByTquestItemId = tquestionitemByTquestItemId;
	}

	public Byte getSquestSolOrder() {
		return this.squestSolOrder;
	}

	public void setSquestSolOrder(Byte squestSolOrder) {
		this.squestSolOrder = squestSolOrder;
	}

	public String getSquestSolComment() {
		return this.squestSolComment;
	}

	public void setSquestSolComment(String squestSolComment) {
		this.squestSolComment = squestSolComment;
	}

}
