package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	private String subjectId;
	private String subjectName;
	private byte subjectCredit;
	private Set<Subjectassignment> subjectassignments = new HashSet<Subjectassignment>(
			0);
	private Set<Subjectandtopic> subjectandtopics = new HashSet<Subjectandtopic>(
			0);

	public Subject() {
	}

	public Subject(String subjectId, String subjectName, byte subjectCredit) {
		this.subjectId = subjectId;
		this.subjectName = subjectName;
		this.subjectCredit = subjectCredit;
	}

	public Subject(String subjectId, String subjectName, byte subjectCredit,
			Set<Subjectassignment> subjectassignments,
			Set<Subjectandtopic> subjectandtopics) {
		this.subjectId = subjectId;
		this.subjectName = subjectName;
		this.subjectCredit = subjectCredit;
		this.subjectassignments = subjectassignments;
		this.subjectandtopics = subjectandtopics;
	}

	public String getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}

	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public byte getSubjectCredit() {
		return this.subjectCredit;
	}

	public void setSubjectCredit(byte subjectCredit) {
		this.subjectCredit = subjectCredit;
	}

	public Set<Subjectassignment> getSubjectassignments() {
		return this.subjectassignments;
	}

	public void setSubjectassignments(Set<Subjectassignment> subjectassignments) {
		this.subjectassignments = subjectassignments;
	}

	public Set<Subjectandtopic> getSubjectandtopics() {
		return this.subjectandtopics;
	}

	public void setSubjectandtopics(Set<Subjectandtopic> subjectandtopics) {
		this.subjectandtopics = subjectandtopics;
	}

}
