package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Subjectassignment generated by hbm2java
 */
public class Subjectassignment implements java.io.Serializable {

	private Integer assignId;
	private Lecturer lecturer;
	private Subject subject;
	private Date assignStartdate;
	private Date assignEnddate;

	public Subjectassignment() {
	}

	public Subjectassignment(Lecturer lecturer, Subject subject,
			Date assignStartdate, Date assignEnddate) {
		this.lecturer = lecturer;
		this.subject = subject;
		this.assignStartdate = assignStartdate;
		this.assignEnddate = assignEnddate;
	}

	public Integer getAssignId() {
		return this.assignId;
	}

	public void setAssignId(Integer assignId) {
		this.assignId = assignId;
	}

	public Lecturer getLecturer() {
		return this.lecturer;
	}

	public void setLecturer(Lecturer lecturer) {
		this.lecturer = lecturer;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public Date getAssignStartdate() {
		return this.assignStartdate;
	}

	public void setAssignStartdate(Date assignStartdate) {
		this.assignStartdate = assignStartdate;
	}

	public Date getAssignEnddate() {
		return this.assignEnddate;
	}

	public void setAssignEnddate(Date assignEnddate) {
		this.assignEnddate = assignEnddate;
	}

}
