package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Subjectandtopic generated by hbm2java
 */
public class Subjectandtopic implements java.io.Serializable {

	private Integer subjectTopId;
	private Topic topic;
	private Subject subject;
	private Float subjectTopPercent;

	public Subjectandtopic() {
	}

	public Subjectandtopic(Topic topic, Subject subject, Float subjectTopPercent) {
		this.topic = topic;
		this.subject = subject;
		this.subjectTopPercent = subjectTopPercent;
	}

	public Integer getSubjectTopId() {
		return this.subjectTopId;
	}

	public void setSubjectTopId(Integer subjectTopId) {
		this.subjectTopId = subjectTopId;
	}

	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public Float getSubjectTopPercent() {
		return this.subjectTopPercent;
	}

	public void setSubjectTopPercent(Float subjectTopPercent) {
		this.subjectTopPercent = subjectTopPercent;
	}

}
