package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Testreview generated by hbm2java
 */
public class Testreview implements java.io.Serializable {

	private Integer testRevId;
	private Test test;
	private Lecturer lecturer;
	private String testRevComment;
	private Date testRevDate;
	private Boolean testRevApproved;

	public Testreview() {
	}

	public Testreview(Test test, Lecturer lecturer, String testRevComment,
			Date testRevDate, Boolean testRevApproved) {
		this.test = test;
		this.lecturer = lecturer;
		this.testRevComment = testRevComment;
		this.testRevDate = testRevDate;
		this.testRevApproved = testRevApproved;
	}

	public Integer getTestRevId() {
		return this.testRevId;
	}

	public void setTestRevId(Integer testRevId) {
		this.testRevId = testRevId;
	}

	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	public Lecturer getLecturer() {
		return this.lecturer;
	}

	public void setLecturer(Lecturer lecturer) {
		this.lecturer = lecturer;
	}

	public String getTestRevComment() {
		return this.testRevComment;
	}

	public void setTestRevComment(String testRevComment) {
		this.testRevComment = testRevComment;
	}

	public Date getTestRevDate() {
		return this.testRevDate;
	}

	public void setTestRevDate(Date testRevDate) {
		this.testRevDate = testRevDate;
	}

	public Boolean getTestRevApproved() {
		return this.testRevApproved;
	}

	public void setTestRevApproved(Boolean testRevApproved) {
		this.testRevApproved = testRevApproved;
	}

}
