package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private Integer testId;
	private Lecturer lecturer;
	private String testDesc;
	private Date testCreationDate;
	private Date testStartTime;
	private Integer testDuration;
	private Set<Testreview> testreviews = new HashSet<Testreview>(0);
	private Set<Studenttestmap> studenttestmaps = new HashSet<Studenttestmap>(0);
	private Set<Testsection> testsections = new HashSet<Testsection>(0);

	public Test() {
	}

	public Test(Lecturer lecturer, String testDesc, Date testCreationDate,
			Date testStartTime, Integer testDuration,
			Set<Testreview> testreviews, Set<Studenttestmap> studenttestmaps,
			Set<Testsection> testsections) {
		this.lecturer = lecturer;
		this.testDesc = testDesc;
		this.testCreationDate = testCreationDate;
		this.testStartTime = testStartTime;
		this.testDuration = testDuration;
		this.testreviews = testreviews;
		this.studenttestmaps = studenttestmaps;
		this.testsections = testsections;
	}

	public Integer getTestId() {
		return this.testId;
	}

	public void setTestId(Integer testId) {
		this.testId = testId;
	}

	public Lecturer getLecturer() {
		return this.lecturer;
	}

	public void setLecturer(Lecturer lecturer) {
		this.lecturer = lecturer;
	}

	public String getTestDesc() {
		return this.testDesc;
	}

	public void setTestDesc(String testDesc) {
		this.testDesc = testDesc;
	}

	public Date getTestCreationDate() {
		return this.testCreationDate;
	}

	public void setTestCreationDate(Date testCreationDate) {
		this.testCreationDate = testCreationDate;
	}

	public Date getTestStartTime() {
		return this.testStartTime;
	}

	public void setTestStartTime(Date testStartTime) {
		this.testStartTime = testStartTime;
	}

	public Integer getTestDuration() {
		return this.testDuration;
	}

	public void setTestDuration(Integer testDuration) {
		this.testDuration = testDuration;
	}

	public Set<Testreview> getTestreviews() {
		return this.testreviews;
	}

	public void setTestreviews(Set<Testreview> testreviews) {
		this.testreviews = testreviews;
	}

	public Set<Studenttestmap> getStudenttestmaps() {
		return this.studenttestmaps;
	}

	public void setStudenttestmaps(Set<Studenttestmap> studenttestmaps) {
		this.studenttestmaps = studenttestmaps;
	}

	public Set<Testsection> getTestsections() {
		return this.testsections;
	}

	public void setTestsections(Set<Testsection> testsections) {
		this.testsections = testsections;
	}

}
