package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Testsection generated by hbm2java
 */
public class Testsection implements java.io.Serializable {

	private Integer testSecId;
	private Test test;
	private String testSecDesc;
	private Set<Tquestion> tquestions = new HashSet<Tquestion>(0);
	private Set<Testsectionitem> testsectionitems = new HashSet<Testsectionitem>(
			0);

	public Testsection() {
	}

	public Testsection(Test test, String testSecDesc,
			Set<Tquestion> tquestions, Set<Testsectionitem> testsectionitems) {
		this.test = test;
		this.testSecDesc = testSecDesc;
		this.tquestions = tquestions;
		this.testsectionitems = testsectionitems;
	}

	public Integer getTestSecId() {
		return this.testSecId;
	}

	public void setTestSecId(Integer testSecId) {
		this.testSecId = testSecId;
	}

	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	public String getTestSecDesc() {
		return this.testSecDesc;
	}

	public void setTestSecDesc(String testSecDesc) {
		this.testSecDesc = testSecDesc;
	}

	public Set<Tquestion> getTquestions() {
		return this.tquestions;
	}

	public void setTquestions(Set<Tquestion> tquestions) {
		this.tquestions = tquestions;
	}

	public Set<Testsectionitem> getTestsectionitems() {
		return this.testsectionitems;
	}

	public void setTestsectionitems(Set<Testsectionitem> testsectionitems) {
		this.testsectionitems = testsectionitems;
	}

}
