package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Topic generated by hbm2java
 */
public class Topic implements java.io.Serializable {

	private String topicId;
	private Topic topic;
	private String topicName;
	private String topicDesc;
	private Set<Topic> topics = new HashSet<Topic>(0);
	private Set<Tquestiontopic> tquestiontopics = new HashSet<Tquestiontopic>(0);
	private Set<Subjectandtopic> subjectandtopics = new HashSet<Subjectandtopic>(
			0);
	private Set<Questiontopic> questiontopics = new HashSet<Questiontopic>(0);

	public Topic() {
	}

	public Topic(String topicId, String topicName) {
		this.topicId = topicId;
		this.topicName = topicName;
	}

	public Topic(String topicId, Topic topic, String topicName,
			String topicDesc, Set<Topic> topics,
			Set<Tquestiontopic> tquestiontopics,
			Set<Subjectandtopic> subjectandtopics,
			Set<Questiontopic> questiontopics) {
		this.topicId = topicId;
		this.topic = topic;
		this.topicName = topicName;
		this.topicDesc = topicDesc;
		this.topics = topics;
		this.tquestiontopics = tquestiontopics;
		this.subjectandtopics = subjectandtopics;
		this.questiontopics = questiontopics;
	}

	public String getTopicId() {
		return this.topicId;
	}

	public void setTopicId(String topicId) {
		this.topicId = topicId;
	}

	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	public String getTopicName() {
		return this.topicName;
	}

	public void setTopicName(String topicName) {
		this.topicName = topicName;
	}

	public String getTopicDesc() {
		return this.topicDesc;
	}

	public void setTopicDesc(String topicDesc) {
		this.topicDesc = topicDesc;
	}

	public Set<Topic> getTopics() {
		return this.topics;
	}

	public void setTopics(Set<Topic> topics) {
		this.topics = topics;
	}

	public Set<Tquestiontopic> getTquestiontopics() {
		return this.tquestiontopics;
	}

	public void setTquestiontopics(Set<Tquestiontopic> tquestiontopics) {
		this.tquestiontopics = tquestiontopics;
	}

	public Set<Subjectandtopic> getSubjectandtopics() {
		return this.subjectandtopics;
	}

	public void setSubjectandtopics(Set<Subjectandtopic> subjectandtopics) {
		this.subjectandtopics = subjectandtopics;
	}

	public Set<Questiontopic> getQuestiontopics() {
		return this.questiontopics;
	}

	public void setQuestiontopics(Set<Questiontopic> questiontopics) {
		this.questiontopics = questiontopics;
	}

}
