package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Tquestionfigure generated by hbm2java
 */
public class Tquestionfigure implements java.io.Serializable {

	private Integer tquestFigId;
	private Tquestion tquestion;
	private Tfigurelink tfigurelink;
	private String tquestFigDesc;

	public Tquestionfigure() {
	}

	public Tquestionfigure(Tquestion tquestion, Tfigurelink tfigurelink,
			String tquestFigDesc) {
		this.tquestion = tquestion;
		this.tfigurelink = tfigurelink;
		this.tquestFigDesc = tquestFigDesc;
	}

	public Integer getTquestFigId() {
		return this.tquestFigId;
	}

	public void setTquestFigId(Integer tquestFigId) {
		this.tquestFigId = tquestFigId;
	}

	public Tquestion getTquestion() {
		return this.tquestion;
	}

	public void setTquestion(Tquestion tquestion) {
		this.tquestion = tquestion;
	}

	public Tfigurelink getTfigurelink() {
		return this.tfigurelink;
	}

	public void setTfigurelink(Tfigurelink tfigurelink) {
		this.tfigurelink = tfigurelink;
	}

	public String getTquestFigDesc() {
		return this.tquestFigDesc;
	}

	public void setTquestFigDesc(String tquestFigDesc) {
		this.tquestFigDesc = tquestFigDesc;
	}

}
