package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Tquestioniteminfo generated by hbm2java
 */
public class Tquestioniteminfo implements java.io.Serializable {

	private Integer tquestItemInfoId;
	private Tquestionitem tquestionitem;
	private String tquestItemInfoProp;
	private String tquestItemInfoValue;

	public Tquestioniteminfo() {
	}

	public Tquestioniteminfo(String tquestItemInfoProp,
			String tquestItemInfoValue) {
		this.tquestItemInfoProp = tquestItemInfoProp;
		this.tquestItemInfoValue = tquestItemInfoValue;
	}

	public Tquestioniteminfo(Tquestionitem tquestionitem,
			String tquestItemInfoProp, String tquestItemInfoValue) {
		this.tquestionitem = tquestionitem;
		this.tquestItemInfoProp = tquestItemInfoProp;
		this.tquestItemInfoValue = tquestItemInfoValue;
	}

	public Integer getTquestItemInfoId() {
		return this.tquestItemInfoId;
	}

	public void setTquestItemInfoId(Integer tquestItemInfoId) {
		this.tquestItemInfoId = tquestItemInfoId;
	}

	public Tquestionitem getTquestionitem() {
		return this.tquestionitem;
	}

	public void setTquestionitem(Tquestionitem tquestionitem) {
		this.tquestionitem = tquestionitem;
	}

	public String getTquestItemInfoProp() {
		return this.tquestItemInfoProp;
	}

	public void setTquestItemInfoProp(String tquestItemInfoProp) {
		this.tquestItemInfoProp = tquestItemInfoProp;
	}

	public String getTquestItemInfoValue() {
		return this.tquestItemInfoValue;
	}

	public void setTquestItemInfoValue(String tquestItemInfoValue) {
		this.tquestItemInfoValue = tquestItemInfoValue;
	}

}
