package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Tquestionowner generated by hbm2java
 */
public class Tquestionowner implements java.io.Serializable {

	private Integer tquestOwnerId;
	private Tquestion tquestion;
	private Lecturer lecturer;

	public Tquestionowner() {
	}

	public Tquestionowner(Tquestion tquestion, Lecturer lecturer) {
		this.tquestion = tquestion;
		this.lecturer = lecturer;
	}

	public Integer getTquestOwnerId() {
		return this.tquestOwnerId;
	}

	public void setTquestOwnerId(Integer tquestOwnerId) {
		this.tquestOwnerId = tquestOwnerId;
	}

	public Tquestion getTquestion() {
		return this.tquestion;
	}

	public void setTquestion(Tquestion tquestion) {
		this.tquestion = tquestion;
	}

	public Lecturer getLecturer() {
		return this.lecturer;
	}

	public void setLecturer(Lecturer lecturer) {
		this.lecturer = lecturer;
	}

}
