package model;// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Tquestionitem generated by hbm2java
 */
public class Tquestionitem implements java.io.Serializable {

	private Integer tquestItemId;
	private Tquestion tquestion;
	private String tquestItemFace;
	private String tquestItemValue;
	private Set<Squestionsolution> squestionsolutionsForTquestNextItemId = new HashSet<Squestionsolution>(
			0);
	private Set<Tquestionsolution> tquestionsolutionsForTquestPreviousItemId = new HashSet<Tquestionsolution>(
			0);
	private Set<Tquestioniteminfo> tquestioniteminfos = new HashSet<Tquestioniteminfo>(
			0);
	private Set<Squestionsolution> squestionsolutionsForTquestPreviousItemId = new HashSet<Squestionsolution>(
			0);
	private Set<Squestionsolution> squestionsolutionsForTquestItemId = new HashSet<Squestionsolution>(
			0);
	private Set<Tquestionsolution> tquestionsolutionsForTquestItemId = new HashSet<Tquestionsolution>(
			0);
	private Set<Tquestionitemfigure> tquestionitemfigures = new HashSet<Tquestionitemfigure>(
			0);
	private Set<Tquestionsolution> tquestionsolutionsForTquestNextItemId = new HashSet<Tquestionsolution>(
			0);

	public Tquestionitem() {
	}

	public Tquestionitem(Tquestion tquestion, String tquestItemFace,
			String tquestItemValue,
			Set<Squestionsolution> squestionsolutionsForTquestNextItemId,
			Set<Tquestionsolution> tquestionsolutionsForTquestPreviousItemId,
			Set<Tquestioniteminfo> tquestioniteminfos,
			Set<Squestionsolution> squestionsolutionsForTquestPreviousItemId,
			Set<Squestionsolution> squestionsolutionsForTquestItemId,
			Set<Tquestionsolution> tquestionsolutionsForTquestItemId,
			Set<Tquestionitemfigure> tquestionitemfigures,
			Set<Tquestionsolution> tquestionsolutionsForTquestNextItemId) {
		this.tquestion = tquestion;
		this.tquestItemFace = tquestItemFace;
		this.tquestItemValue = tquestItemValue;
		this.squestionsolutionsForTquestNextItemId = squestionsolutionsForTquestNextItemId;
		this.tquestionsolutionsForTquestPreviousItemId = tquestionsolutionsForTquestPreviousItemId;
		this.tquestioniteminfos = tquestioniteminfos;
		this.squestionsolutionsForTquestPreviousItemId = squestionsolutionsForTquestPreviousItemId;
		this.squestionsolutionsForTquestItemId = squestionsolutionsForTquestItemId;
		this.tquestionsolutionsForTquestItemId = tquestionsolutionsForTquestItemId;
		this.tquestionitemfigures = tquestionitemfigures;
		this.tquestionsolutionsForTquestNextItemId = tquestionsolutionsForTquestNextItemId;
	}

	public Integer getTquestItemId() {
		return this.tquestItemId;
	}

	public void setTquestItemId(Integer tquestItemId) {
		this.tquestItemId = tquestItemId;
	}

	public Tquestion getTquestion() {
		return this.tquestion;
	}

	public void setTquestion(Tquestion tquestion) {
		this.tquestion = tquestion;
	}

	public String getTquestItemFace() {
		return this.tquestItemFace;
	}

	public void setTquestItemFace(String tquestItemFace) {
		this.tquestItemFace = tquestItemFace;
	}

	public String getTquestItemValue() {
		return this.tquestItemValue;
	}

	public void setTquestItemValue(String tquestItemValue) {
		this.tquestItemValue = tquestItemValue;
	}

	public Set<Squestionsolution> getSquestionsolutionsForTquestNextItemId() {
		return this.squestionsolutionsForTquestNextItemId;
	}

	public void setSquestionsolutionsForTquestNextItemId(
			Set<Squestionsolution> squestionsolutionsForTquestNextItemId) {
		this.squestionsolutionsForTquestNextItemId = squestionsolutionsForTquestNextItemId;
	}

	public Set<Tquestionsolution> getTquestionsolutionsForTquestPreviousItemId() {
		return this.tquestionsolutionsForTquestPreviousItemId;
	}

	public void setTquestionsolutionsForTquestPreviousItemId(
			Set<Tquestionsolution> tquestionsolutionsForTquestPreviousItemId) {
		this.tquestionsolutionsForTquestPreviousItemId = tquestionsolutionsForTquestPreviousItemId;
	}

	public Set<Tquestioniteminfo> getTquestioniteminfos() {
		return this.tquestioniteminfos;
	}

	public void setTquestioniteminfos(Set<Tquestioniteminfo> tquestioniteminfos) {
		this.tquestioniteminfos = tquestioniteminfos;
	}

	public Set<Squestionsolution> getSquestionsolutionsForTquestPreviousItemId() {
		return this.squestionsolutionsForTquestPreviousItemId;
	}

	public void setSquestionsolutionsForTquestPreviousItemId(
			Set<Squestionsolution> squestionsolutionsForTquestPreviousItemId) {
		this.squestionsolutionsForTquestPreviousItemId = squestionsolutionsForTquestPreviousItemId;
	}

	public Set<Squestionsolution> getSquestionsolutionsForTquestItemId() {
		return this.squestionsolutionsForTquestItemId;
	}

	public void setSquestionsolutionsForTquestItemId(
			Set<Squestionsolution> squestionsolutionsForTquestItemId) {
		this.squestionsolutionsForTquestItemId = squestionsolutionsForTquestItemId;
	}

	public Set<Tquestionsolution> getTquestionsolutionsForTquestItemId() {
		return this.tquestionsolutionsForTquestItemId;
	}

	public void setTquestionsolutionsForTquestItemId(
			Set<Tquestionsolution> tquestionsolutionsForTquestItemId) {
		this.tquestionsolutionsForTquestItemId = tquestionsolutionsForTquestItemId;
	}

	public Set<Tquestionitemfigure> getTquestionitemfigures() {
		return this.tquestionitemfigures;
	}

	public void setTquestionitemfigures(
			Set<Tquestionitemfigure> tquestionitemfigures) {
		this.tquestionitemfigures = tquestionitemfigures;
	}

	public Set<Tquestionsolution> getTquestionsolutionsForTquestNextItemId() {
		return this.tquestionsolutionsForTquestNextItemId;
	}

	public void setTquestionsolutionsForTquestNextItemId(
			Set<Tquestionsolution> tquestionsolutionsForTquestNextItemId) {
		this.tquestionsolutionsForTquestNextItemId = tquestionsolutionsForTquestNextItemId;
	}

}
