package model;

// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Tquestiontopic generated by hbm2java
 */
public class Tquestiontopic implements java.io.Serializable {

	private Integer tquestTopicId;
	private Topic topic;
	private Tquestion tquestion;
	private Character tquestTopicLevel;

	public Tquestiontopic() {
	}

	public Tquestiontopic(Topic topic, Tquestion tquestion,
			Character tquestTopicLevel) {
		this.topic = topic;
		this.tquestion = tquestion;
		this.tquestTopicLevel = tquestTopicLevel;
	}

	public Integer getTquestTopicId() {
		return this.tquestTopicId;
	}

	public void setTquestTopicId(Integer tquestTopicId) {
		this.tquestTopicId = tquestTopicId;
	}

	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	public Tquestion getTquestion() {
		return this.tquestion;
	}

	public void setTquestion(Tquestion tquestion) {
		this.tquestion = tquestion;
	}

	public Character getTquestTopicLevel() {
		return this.tquestTopicLevel;
	}

	public void setTquestTopicLevel(Character tquestTopicLevel) {
		this.tquestTopicLevel = tquestTopicLevel;
	}

}
