package model;
// default package
// Generated Mar 12, 2014 10:45:56 PM by Hibernate Tools 3.6.0

/**
 * Tquestionsolution generated by hbm2java
 */
public class Tquestionsolution implements java.io.Serializable {

	private Integer tquestSolId;
	private Tquestionitem tquestionitemByTquestNextItemId;
	private Tquestionitem tquestionitemByTquestPreviousItemId;
	private Tquestion tquestion;
	private Tquestionitem tquestionitemByTquestItemId;
	private Byte tquestSolOrder;

	public Tquestionsolution() {
	}

	public Tquestionsolution(Tquestionitem tquestionitemByTquestNextItemId,
			Tquestionitem tquestionitemByTquestPreviousItemId,
			Tquestion tquestion, Tquestionitem tquestionitemByTquestItemId,
			Byte tquestSolOrder) {
		this.tquestionitemByTquestNextItemId = tquestionitemByTquestNextItemId;
		this.tquestionitemByTquestPreviousItemId = tquestionitemByTquestPreviousItemId;
		this.tquestion = tquestion;
		this.tquestionitemByTquestItemId = tquestionitemByTquestItemId;
		this.tquestSolOrder = tquestSolOrder;
	}

	public Integer getTquestSolId() {
		return this.tquestSolId;
	}

	public void setTquestSolId(Integer tquestSolId) {
		this.tquestSolId = tquestSolId;
	}

	public Tquestionitem getTquestionitemByTquestNextItemId() {
		return this.tquestionitemByTquestNextItemId;
	}

	public void setTquestionitemByTquestNextItemId(
			Tquestionitem tquestionitemByTquestNextItemId) {
		this.tquestionitemByTquestNextItemId = tquestionitemByTquestNextItemId;
	}

	public Tquestionitem getTquestionitemByTquestPreviousItemId() {
		return this.tquestionitemByTquestPreviousItemId;
	}

	public void setTquestionitemByTquestPreviousItemId(
			Tquestionitem tquestionitemByTquestPreviousItemId) {
		this.tquestionitemByTquestPreviousItemId = tquestionitemByTquestPreviousItemId;
	}

	public Tquestion getTquestion() {
		return this.tquestion;
	}

	public void setTquestion(Tquestion tquestion) {
		this.tquestion = tquestion;
	}

	public Tquestionitem getTquestionitemByTquestItemId() {
		return this.tquestionitemByTquestItemId;
	}

	public void setTquestionitemByTquestItemId(
			Tquestionitem tquestionitemByTquestItemId) {
		this.tquestionitemByTquestItemId = tquestionitemByTquestItemId;
	}

	public Byte getTquestSolOrder() {
		return this.tquestSolOrder;
	}

	public void setTquestSolOrder(Byte tquestSolOrder) {
		this.tquestSolOrder = tquestSolOrder;
	}

}
