package com.bosch.rts.entity;

// Generated Dec 5, 2011 4:41:58 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;

import com.bosch.rts.utilities.RTSConstants;

/**
 * HrResult generated by hbm2java.
 */
@Entity
@Table(name = "trts_hr_result")
public class HrResult implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 8003045567911648758L;
	
	/** The ihr hr result id. */
	private Integer ihrHrResultId;
	
	/** The interview schedule. */
	private InterviewSchedule interviewSchedule;	
	
	/** The ihr academic degree. */
	private String ihrAcademicDegree;
	
	/** The ihr academic certification. */
	private String ihrAcademicCertification;
	
	/** The ihr academic master. */
	private String ihrAcademicMaster;
	
	/** The ihr academic other. */
	private String ihrAcademicOther;
	
	/** The ihr foreign language. */
	private Boolean ihrForeignLanguage;
	
	/** The ihr foreign language detail. */
	private String ihrForeignLanguageDetail;
	
	/** The ihr current role. */
	private String ihrCurrentRole;
	
	/** The ihr current company. */
	private String ihrCurrentCompany;
	
	/** The ihr years of exp total. */
	private String ihrYearsOfExpTotal;
	
	/** The ihr years of exp rel. */
	private String ihrYearsOfExpRel;
	
	/** The ihr overseas exp location1. */
	private String ihrOverseasExpLocation1;
	
	/** The ihr overseas exp duration1. */
	private String ihrOverseasExpDuration1;
	
	/** The ihr overseas exp location2. */
	private String ihrOverseasExpLocation2;
	
	/** The ihr overseas exp duration2. */
	private String ihrOverseasExpDuration2;
	
	/** The ihr overseas exp location3. */
	private String ihrOverseasExpLocation3;
	
	/** The ihr overseas exp duration3. */
	private String ihrOverseasExpDuration3;
	
	/** The ihr general attitude. */
	private String ihrGeneralAttitude;
	
	/** The ihr articulation. */
	private String ihrArticulation;
	
	/** The ihr communication. */
	private String ihrCommunication;
	
	/** The ihr flexibility. */
	private String ihrFlexibility;
	
	/** The ihr leadership. */
	private String ihrLeadership;
	
	/** The ihr personality. */
	private String ihrPersonality;
	
	/** The ihr service stability. */
	private String ihrServiceStability;
	
	/** The ihr key strength. */
	private String ihrKeyStrength;
	
	/** The ihr areas to improve. */
	private String ihrAreasToImprove;
	
	/** The ihr current salary fixed. */
	private String ihrCurrentSalaryFixed;
	
	/** The ihr current salary variable. */
	private String ihrCurrentSalaryVariable;
	
	/** The ihr expected salary. */
	private String ihrExpectedSalary;
	
	/** The ihr other expectation. */
	private String ihrOtherExpectation;
	
	/** The ihr reason for change. */
	private String ihrReasonForChange;
	
	/** The ihr career plan3yrs. */
	private String ihrCareerPlan3yrs;
	
	/** The ihr career plan5yrs. */
	private String ihrCareerPlan5yrs;
	
	/** The ihr motivating factor. */
	private String ihrMotivatingFactor;
	
	/** The ihr technical skill. */
	private String ihrTechnicalSkill;
	
	/** The ihr offer in hand. */
	private Boolean ihrOfferInHand;
	
	/** The ihr offer in hand detail. */
	private String ihrOfferInHandDetail;
	
	/** The ihr location preference. */
	private String ihrLocationPreference;
	
	/** The ihr current bond. */
	private Boolean ihrCurrentBond;
	
	/** The ihr current bond duration. */
	private String ihrCurrentBondDuration;
	
	/** The ihr current bond amount. */
	private String ihrCurrentBondAmount;
	
	/** The ihr contractual model. */
	private Boolean ihrContractualModel;
	
	/** The ihr notice period days. */
	private Integer ihrNoticePeriodDays;
	
	/** The ihr notice period date. */
	private Date ihrNoticePeriodDate;
	
	/** The ihr passport detail. */
	private String ihrPassportDetail;
	
	/** The ihr application form. */
	private String ihrApplicationForm;
	
	/** The ihr recommended. */
	private String ihrRecommended;
	
	/** The ihr father. */
	private String ihrFather;
	
	/** The ihr mother. */
	private String ihrMother;
	
	/** The ihr spouse. */
	private String ihrSpouse;
	
	/** The ihr children. */
	private String ihrChildren;
	
	/** The ihr sibling. */
	private String ihrSibling;
	
	/** The ihr comment. */
	private String ihrComment;
	
	/** The ihrforeign language know. */
	private String ihrforeignLanguageKnow;
	
	/** The its created by. */
	private String createdBy;
	
	/** The its created on. */
	private Date createdOn;
	
	/** The its updated by. */
	private String updatedBy;
	
	/** The its updated on. */
	private Date updatedOn;		
	
	/**
	 * @return the createdBy
	 */
	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * @param createdBy the createdBy to set
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * @return the createdOn
	 */
	@Column(name = "created_on")
	public Date getCreatedOn() {
		return this.createdOn;
	}

	/**
	 * @param createdOn the createdOn to set
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * @return the updatedBy
	 */
	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	/**
	 * @param updatedBy the updatedBy to set
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * @return the updatedOn
	 */
	@Column(name = "updated_on")
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	/**
	 * @param updatedOn the updatedOn to set
	 */
	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	/**
	 * Instantiates a new hr result.
	 */
	public HrResult() {
	}

	/**
	 * Instantiates a new hr result.
	 *
	 * @param ihrItsInterviewScheduleId the ihr its interview schedule id
	 * @param ihrUrsCreatedByUser the ihr urs created by user
	 */
	public HrResult(int ihrItsInterviewScheduleId, int ihrUrsCreatedByUser) {
	}

	/**
	 * Instantiates a new hr result.
	 *
	 * @param ihrItsInterviewScheduleId the ihr its interview schedule id
	 * @param ihrUrsCreatedByUser the ihr urs created by user
	 * @param ihrAcademicDegree the ihr academic degree
	 * @param ihrAcademicCertification the ihr academic certification
	 * @param ihrAcademicMaster the ihr academic master
	 * @param ihrAcademicOther the ihr academic other
	 * @param ihrForeignLanguage the ihr foreign language
	 * @param ihrForeignLanguageDetail the ihr foreign language detail
	 * @param ihrCurrentRole the ihr current role
	 * @param ihrCurrentCompany the ihr current company
	 * @param ihrYearsOfExpTotal the ihr years of exp total
	 * @param ihrYearsOfExpRel the ihr years of exp rel
	 * @param ihrOverseasExpLocation1 the ihr overseas exp location1
	 * @param ihrOverseasExpDuration1 the ihr overseas exp duration1
	 * @param ihrOverseasExpLocation2 the ihr overseas exp location2
	 * @param ihrOverseasExpDuration2 the ihr overseas exp duration2
	 * @param ihrOverseasExpLocation3 the ihr overseas exp location3
	 * @param ihrOverseasExpDuration3 the ihr overseas exp duration3
	 * @param ihrGeneralAttitude the ihr general attitude
	 * @param ihrArticulation the ihr articulation
	 * @param ihrCommunication the ihr communication
	 * @param ihrFlexibility the ihr flexibility
	 * @param ihrLeadership the ihr leadership
	 * @param ihrPersonality the ihr personality
	 * @param ihrServiceStability the ihr service stability
	 * @param ihrKeyStrength the ihr key strength
	 * @param ihrAreasToImprove the ihr areas to improve
	 * @param ihrCurrentSalaryFixed the ihr current salary fixed
	 * @param ihrCurrentSalaryVariable the ihr current salary variable
	 * @param ihrExpectedSalary the ihr expected salary
	 * @param ihrOtherExpectation the ihr other expectation
	 * @param ihrReasonForChange the ihr reason for change
	 * @param ihrCareerPlan3yrs the ihr career plan3yrs
	 * @param ihrCareerPlan5yrs the ihr career plan5yrs
	 * @param ihrMotivatingFactor the ihr motivating factor
	 * @param ihrTechnicalSkill the ihr technical skill
	 * @param ihrOfferInHand the ihr offer in hand
	 * @param ihrOfferInHandDetail the ihr offer in hand detail
	 * @param ihrLocationPreference the ihr location preference
	 * @param ihrCurrentBond the ihr current bond
	 * @param ihrCurrentBondDuration the ihr current bond duration
	 * @param ihrCurrentBondAmount the ihr current bond amount
	 * @param ihrContractualModel the ihr contractual model
	 * @param ihrNoticePeriodDays the ihr notice period days
	 * @param ihrNoticePeriodDate the ihr notice period date
	 * @param ihrPassportDetail the ihr passport detail
	 * @param ihrApplicationForm the ihr application form
	 * @param ihrRecommended the ihr recommended
	 * @param ihrFather the ihr father
	 * @param ihrMother the ihr mother
	 * @param ihrSpouse the ihr spouse
	 * @param ihrChildren the ihr children
	 * @param ihrSibling the ihr sibling
	 * @param ihrComment the ihr comment
	 * @param shrHrResultId the shr hr result id
	 * @param shrItsInterviewScheduleId the shr its interview schedule id
	 */
	public HrResult(int ihrItsInterviewScheduleId, String createdBy, Date createdOn,
			String ihrAcademicDegree, String ihrAcademicCertification,
			String ihrAcademicMaster, String ihrAcademicOther,
			Boolean ihrForeignLanguage, String ihrForeignLanguageDetail,
			String ihrCurrentRole, String ihrCurrentCompany,
			String ihrYearsOfExpTotal, String ihrYearsOfExpRel,
			String ihrOverseasExpLocation1, String ihrOverseasExpDuration1,
			String ihrOverseasExpLocation2, String ihrOverseasExpDuration2,
			String ihrOverseasExpLocation3, String ihrOverseasExpDuration3,
			String ihrGeneralAttitude, String ihrArticulation,
			String ihrCommunication, String ihrFlexibility,
			String ihrLeadership, String ihrPersonality,
			String ihrServiceStability, String ihrKeyStrength,
			String ihrAreasToImprove, String ihrCurrentSalaryFixed,
			String ihrCurrentSalaryVariable, String ihrExpectedSalary,
			String ihrOtherExpectation, String ihrReasonForChange,
			String ihrCareerPlan3yrs, String ihrCareerPlan5yrs,
			String ihrMotivatingFactor, String ihrTechnicalSkill,
			Boolean ihrOfferInHand, String ihrOfferInHandDetail,
			String ihrLocationPreference, Boolean ihrCurrentBond,
			String ihrCurrentBondDuration, String ihrCurrentBondAmount,
			Boolean ihrContractualModel, Integer ihrNoticePeriodDays,
			Date ihrNoticePeriodDate, String ihrPassportDetail,
			String ihrApplicationForm, String ihrRecommended, String ihrFather,
			String ihrMother, String ihrSpouse, String ihrChildren,
			String ihrSibling, String ihrComment, Integer shrHrResultId,
			Integer shrItsInterviewScheduleId) {
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.ihrAcademicDegree = ihrAcademicDegree;
		this.ihrAcademicCertification = ihrAcademicCertification;
		this.ihrAcademicMaster = ihrAcademicMaster;
		this.ihrAcademicOther = ihrAcademicOther;
		this.ihrForeignLanguage = ihrForeignLanguage;
		this.ihrForeignLanguageDetail = ihrForeignLanguageDetail;
		this.ihrCurrentRole = ihrCurrentRole;
		this.ihrCurrentCompany = ihrCurrentCompany;
		this.ihrYearsOfExpTotal = ihrYearsOfExpTotal;
		this.ihrYearsOfExpRel = ihrYearsOfExpRel;
		this.ihrOverseasExpLocation1 = ihrOverseasExpLocation1;
		this.ihrOverseasExpDuration1 = ihrOverseasExpDuration1;
		this.ihrOverseasExpLocation2 = ihrOverseasExpLocation2;
		this.ihrOverseasExpDuration2 = ihrOverseasExpDuration2;
		this.ihrOverseasExpLocation3 = ihrOverseasExpLocation3;
		this.ihrOverseasExpDuration3 = ihrOverseasExpDuration3;
		this.ihrGeneralAttitude = ihrGeneralAttitude;
		this.ihrArticulation = ihrArticulation;
		this.ihrCommunication = ihrCommunication;
		this.ihrFlexibility = ihrFlexibility;
		this.ihrLeadership = ihrLeadership;
		this.ihrPersonality = ihrPersonality;
		this.ihrServiceStability = ihrServiceStability;
		this.ihrKeyStrength = ihrKeyStrength;
		this.ihrAreasToImprove = ihrAreasToImprove;
		this.ihrCurrentSalaryFixed = ihrCurrentSalaryFixed;
		this.ihrCurrentSalaryVariable = ihrCurrentSalaryVariable;
		this.ihrExpectedSalary = ihrExpectedSalary;
		this.ihrOtherExpectation = ihrOtherExpectation;
		this.ihrReasonForChange = ihrReasonForChange;
		this.ihrCareerPlan3yrs = ihrCareerPlan3yrs;
		this.ihrCareerPlan5yrs = ihrCareerPlan5yrs;
		this.ihrMotivatingFactor = ihrMotivatingFactor;
		this.ihrTechnicalSkill = ihrTechnicalSkill;
		this.ihrOfferInHand = ihrOfferInHand;
		this.ihrOfferInHandDetail = ihrOfferInHandDetail;
		this.ihrLocationPreference = ihrLocationPreference;
		this.ihrCurrentBond = ihrCurrentBond;
		this.ihrCurrentBondDuration = ihrCurrentBondDuration;
		this.ihrCurrentBondAmount = ihrCurrentBondAmount;
		this.ihrContractualModel = ihrContractualModel;
		this.ihrNoticePeriodDays = ihrNoticePeriodDays;
		this.ihrNoticePeriodDate = ihrNoticePeriodDate;
		this.ihrPassportDetail = ihrPassportDetail;
		this.ihrApplicationForm = ihrApplicationForm;
		this.ihrRecommended = ihrRecommended;
		this.ihrFather = ihrFather;
		this.ihrMother = ihrMother;
		this.ihrSpouse = ihrSpouse;
		this.ihrChildren = ihrChildren;
		this.ihrSibling = ihrSibling;
		this.ihrComment = ihrComment;
	}

	/**
	 * Gets the ihr hr result id.
	 *
	 * @return the ihr hr result id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ihr_hr_result_id", unique = true, nullable = false)
	public Integer getIhrHrResultId() {
		return this.ihrHrResultId;
	}

	/**
	 * Sets the ihr hr result id.
	 *
	 * @param ihrHrResultId the new ihr hr result id
	 */
	public void setIhrHrResultId(Integer ihrHrResultId) {
		this.ihrHrResultId = ihrHrResultId;
	}


	/**
	 * Gets the ihr academic degree.
	 *
	 * @return the ihr academic degree
	 */
	@Column(name = "ihr_academic_degree", length = 15)
	@Length(max = 15)
	public String getIhrAcademicDegree() {
		return this.ihrAcademicDegree;
	}

	/**
	 * Sets the ihr academic degree.
	 *
	 * @param ihrAcademicDegree the new ihr academic degree
	 */
	public void setIhrAcademicDegree(String ihrAcademicDegree) {
		this.ihrAcademicDegree = ihrAcademicDegree;
	}

	/**
	 * Gets the ihr academic certification.
	 *
	 * @return the ihr academic certification
	 */
	@Column(name = "ihr_academic_certification", length = 15)
	@Length(max = 15)
	public String getIhrAcademicCertification() {
		return this.ihrAcademicCertification;
	}

	/**
	 * Sets the ihr academic certification.
	 *
	 * @param ihrAcademicCertification the new ihr academic certification
	 */
	public void setIhrAcademicCertification(String ihrAcademicCertification) {
		this.ihrAcademicCertification = ihrAcademicCertification;
	}

	/**
	 * Gets the ihr academic master.
	 *
	 * @return the ihr academic master
	 */
	@Column(name = "ihr_academic_master", length = 15)
	@Length(max = 15)
	public String getIhrAcademicMaster() {
		return this.ihrAcademicMaster;
	}

	/**
	 * Sets the ihr academic master.
	 *
	 * @param ihrAcademicMaster the new ihr academic master
	 */
	public void setIhrAcademicMaster(String ihrAcademicMaster) {
		this.ihrAcademicMaster = ihrAcademicMaster;
	}

	/**
	 * Gets the ihr academic other.
	 *
	 * @return the ihr academic other
	 */
	@Column(name = "ihr_academic_other", length = 15)
	@Length(max = 15)
	public String getIhrAcademicOther() {
		return this.ihrAcademicOther;
	}

	/**
	 * Sets the ihr academic other.
	 *
	 * @param ihrAcademicOther the new ihr academic other
	 */
	public void setIhrAcademicOther(String ihrAcademicOther) {
		this.ihrAcademicOther = ihrAcademicOther;
	}

	/**
	 * Gets the ihr foreign language.
	 *
	 * @return the ihr foreign language
	 */
	@Column(name = "ihr_foreign_language")
	public Boolean getIhrForeignLanguage() {
		return this.ihrForeignLanguage;
	}

	/**
	 * Sets the ihr foreign language.
	 *
	 * @param ihrForeignLanguage the new ihr foreign language
	 */
	public void setIhrForeignLanguage(Boolean ihrForeignLanguage) {
		this.ihrForeignLanguage = ihrForeignLanguage;
	}

	/**
	 * Gets the ihr foreign language detail.
	 *
	 * @return the ihr foreign language detail
	 */
	@Column(name = "ihr_foreign_language_detail", length = 45)
	@Length(max = 45)
	public String getIhrForeignLanguageDetail() {
		return this.ihrForeignLanguageDetail;
	}

	/**
	 * Sets the ihr foreign language detail.
	 *
	 * @param ihrForeignLanguageDetail the new ihr foreign language detail
	 */
	public void setIhrForeignLanguageDetail(String ihrForeignLanguageDetail) {
		this.ihrForeignLanguageDetail = ihrForeignLanguageDetail;
	}

	/**
	 * Gets the ihr current role.
	 *
	 * @return the ihr current role
	 */
	@Column(name = "ihr_current_role", length = 250)
	@Length(max = 250)
	public String getIhrCurrentRole() {
		return this.ihrCurrentRole;
	}

	/**
	 * Sets the ihr current role.
	 *
	 * @param ihrCurrentRole the new ihr current role
	 */
	public void setIhrCurrentRole(String ihrCurrentRole) {
		this.ihrCurrentRole = ihrCurrentRole;
	}

	/**
	 * Gets the ihr current company.
	 *
	 * @return the ihr current company
	 */
	@Column(name = "ihr_current_company", length = 250)
	@Length(max = 250)
	public String getIhrCurrentCompany() {
		return this.ihrCurrentCompany;
	}

	/**
	 * Sets the ihr current company.
	 *
	 * @param ihrCurrentCompany the new ihr current company
	 */
	public void setIhrCurrentCompany(String ihrCurrentCompany) {
		this.ihrCurrentCompany = ihrCurrentCompany;
	}

	/**
	 * Gets the ihr years of exp total.
	 *
	 * @return the ihr years of exp total
	 */
	@Column(name = "ihr_years_of_exp_total", length = 15)
	@Length(max = 15)
	public String getIhrYearsOfExpTotal() {
		return this.ihrYearsOfExpTotal;
	}

	/**
	 * Sets the ihr years of exp total.
	 *
	 * @param ihrYearsOfExpTotal the new ihr years of exp total
	 */
	public void setIhrYearsOfExpTotal(String ihrYearsOfExpTotal) {
		this.ihrYearsOfExpTotal = ihrYearsOfExpTotal;
	}

	/**
	 * Gets the ihr years of exp rel.
	 *
	 * @return the ihr years of exp rel
	 */
	@Column(name = "ihr_years_of_exp_rel", length = 15)
	@Length(max = 15)
	public String getIhrYearsOfExpRel() {
		return this.ihrYearsOfExpRel;
	}

	/**
	 * Sets the ihr years of exp rel.
	 *
	 * @param ihrYearsOfExpRel the new ihr years of exp rel
	 */
	public void setIhrYearsOfExpRel(String ihrYearsOfExpRel) {
		this.ihrYearsOfExpRel = ihrYearsOfExpRel;
	}

	/**
	 * Gets the ihr overseas exp location1.
	 *
	 * @return the ihr overseas exp location1
	 */
	@Column(name = "ihr_overseas_exp_location_1", length = 15)
	@Length(max = 15)
	public String getIhrOverseasExpLocation1() {
		return this.ihrOverseasExpLocation1;
	}

	/**
	 * Sets the ihr overseas exp location1.
	 *
	 * @param ihrOverseasExpLocation1 the new ihr overseas exp location1
	 */
	public void setIhrOverseasExpLocation1(String ihrOverseasExpLocation1) {
		this.ihrOverseasExpLocation1 = ihrOverseasExpLocation1;
	}

	/**
	 * Gets the ihr overseas exp duration1.
	 *
	 * @return the ihr overseas exp duration1
	 */
	@Column(name = "ihr_overseas_exp_duration_1", length = 15)
	@Length(max = 15)
	public String getIhrOverseasExpDuration1() {
		return this.ihrOverseasExpDuration1;
	}

	/**
	 * Sets the ihr overseas exp duration1.
	 *
	 * @param ihrOverseasExpDuration1 the new ihr overseas exp duration1
	 */
	public void setIhrOverseasExpDuration1(String ihrOverseasExpDuration1) {
		this.ihrOverseasExpDuration1 = ihrOverseasExpDuration1;
	}

	/**
	 * Gets the ihr overseas exp location2.
	 *
	 * @return the ihr overseas exp location2
	 */
	@Column(name = "ihr_overseas_exp_location_2", length = 15)
	@Length(max = 15)
	public String getIhrOverseasExpLocation2() {
		return this.ihrOverseasExpLocation2;
	}

	/**
	 * Sets the ihr overseas exp location2.
	 *
	 * @param ihrOverseasExpLocation2 the new ihr overseas exp location2
	 */
	public void setIhrOverseasExpLocation2(String ihrOverseasExpLocation2) {
		this.ihrOverseasExpLocation2 = ihrOverseasExpLocation2;
	}

	/**
	 * Gets the ihr overseas exp duration2.
	 *
	 * @return the ihr overseas exp duration2
	 */
	@Column(name = "ihr_overseas_exp_duration_2", length = 15)
	@Length(max = 15)
	public String getIhrOverseasExpDuration2() {
		return this.ihrOverseasExpDuration2;
	}

	/**
	 * Sets the ihr overseas exp duration2.
	 *
	 * @param ihrOverseasExpDuration2 the new ihr overseas exp duration2
	 */
	public void setIhrOverseasExpDuration2(String ihrOverseasExpDuration2) {
		this.ihrOverseasExpDuration2 = ihrOverseasExpDuration2;
	}

	/**
	 * Gets the ihr overseas exp location3.
	 *
	 * @return the ihr overseas exp location3
	 */
	@Column(name = "ihr_overseas_exp_location_3", length = 15)
	@Length(max = 15)
	public String getIhrOverseasExpLocation3() {
		return this.ihrOverseasExpLocation3;
	}

	/**
	 * Sets the ihr overseas exp location3.
	 *
	 * @param ihrOverseasExpLocation3 the new ihr overseas exp location3
	 */
	public void setIhrOverseasExpLocation3(String ihrOverseasExpLocation3) {
		this.ihrOverseasExpLocation3 = ihrOverseasExpLocation3;
	}

	/**
	 * Gets the ihr overseas exp duration3.
	 *
	 * @return the ihr overseas exp duration3
	 */
	@Column(name = "ihr_overseas_exp_duration_3", length = 15)
	@Length(max = 15)
	public String getIhrOverseasExpDuration3() {
		return this.ihrOverseasExpDuration3;
	}

	/**
	 * Sets the ihr overseas exp duration3.
	 *
	 * @param ihrOverseasExpDuration3 the new ihr overseas exp duration3
	 */
	public void setIhrOverseasExpDuration3(String ihrOverseasExpDuration3) {
		this.ihrOverseasExpDuration3 = ihrOverseasExpDuration3;
	}

	/**
	 * Gets the ihr general attitude.
	 *
	 * @return the ihr general attitude
	 */
	@Column(name = "ihr_general_attitude", length = 250)
	@Length(max = 250)
	public String getIhrGeneralAttitude() {
		return this.ihrGeneralAttitude;
	}

	/**
	 * Sets the ihr general attitude.
	 *
	 * @param ihrGeneralAttitude the new ihr general attitude
	 */
	public void setIhrGeneralAttitude(String ihrGeneralAttitude) {
		this.ihrGeneralAttitude = ihrGeneralAttitude;
	}

	/**
	 * Gets the ihr articulation.
	 *
	 * @return the ihr articulation
	 */
	@Column(name = "ihr_articulation", length = 250)
	@Length(max = 250)
	public String getIhrArticulation() {
		return this.ihrArticulation;
	}

	/**
	 * Sets the ihr articulation.
	 *
	 * @param ihrArticulation the new ihr articulation
	 */
	public void setIhrArticulation(String ihrArticulation) {
		this.ihrArticulation = ihrArticulation;
	}

	/**
	 * Gets the ihr communication.
	 *
	 * @return the ihr communication
	 */
	@Column(name = "ihr_communication", length = 250)
	@Length(max = 250)
	public String getIhrCommunication() {
		return this.ihrCommunication;
	}

	/**
	 * Sets the ihr communication.
	 *
	 * @param ihrCommunication the new ihr communication
	 */
	public void setIhrCommunication(String ihrCommunication) {
		this.ihrCommunication = ihrCommunication;
	}

	/**
	 * Gets the ihr flexibility.
	 *
	 * @return the ihr flexibility
	 */
	@Column(name = "ihr_flexibility", length = 250)
	@Length(max = 250)
	public String getIhrFlexibility() {
		return this.ihrFlexibility;
	}

	/**
	 * Sets the ihr flexibility.
	 *
	 * @param ihrFlexibility the new ihr flexibility
	 */
	public void setIhrFlexibility(String ihrFlexibility) {
		this.ihrFlexibility = ihrFlexibility;
	}

	/**
	 * Gets the ihr leadership.
	 *
	 * @return the ihr leadership
	 */
	@Column(name = "ihr_leadership", length = 250)
	@Length(max = 250)
	public String getIhrLeadership() {
		return this.ihrLeadership;
	}

	/**
	 * Sets the ihr leadership.
	 *
	 * @param ihrLeadership the new ihr leadership
	 */
	public void setIhrLeadership(String ihrLeadership) {
		this.ihrLeadership = ihrLeadership;
	}

	/**
	 * Gets the ihr personality.
	 *
	 * @return the ihr personality
	 */
	@Column(name = "ihr_personality", length = 250)
	@Length(max = 250)
	public String getIhrPersonality() {
		return this.ihrPersonality;
	}

	/**
	 * Sets the ihr personality.
	 *
	 * @param ihrPersonality the new ihr personality
	 */
	public void setIhrPersonality(String ihrPersonality) {
		this.ihrPersonality = ihrPersonality;
	}

	/**
	 * Gets the ihr service stability.
	 *
	 * @return the ihr service stability
	 */
	@Column(name = "ihr_service_stability", length = 250)
	@Length(max = 250)
	public String getIhrServiceStability() {
		return this.ihrServiceStability;
	}

	/**
	 * Sets the ihr service stability.
	 *
	 * @param ihrServiceStability the new ihr service stability
	 */
	public void setIhrServiceStability(String ihrServiceStability) {
		this.ihrServiceStability = ihrServiceStability;
	}

	/**
	 * Gets the ihr key strength.
	 *
	 * @return the ihr key strength
	 */
	@Column(name = "ihr_key_strength", length = 250)
	@Length(max = 250)
	public String getIhrKeyStrength() {
		return this.ihrKeyStrength;
	}

	/**
	 * Sets the ihr key strength.
	 *
	 * @param ihrKeyStrength the new ihr key strength
	 */
	public void setIhrKeyStrength(String ihrKeyStrength) {
		this.ihrKeyStrength = ihrKeyStrength;
	}

	/**
	 * Gets the ihr areas to improve.
	 *
	 * @return the ihr areas to improve
	 */
	@Column(name = "ihr_areas_to_improve", length = 250)
	@Length(max = 250)
	public String getIhrAreasToImprove() {
		return this.ihrAreasToImprove;
	}

	/**
	 * Sets the ihr areas to improve.
	 *
	 * @param ihrAreasToImprove the new ihr areas to improve
	 */
	public void setIhrAreasToImprove(String ihrAreasToImprove) {
		this.ihrAreasToImprove = ihrAreasToImprove;
	}

	/**
	 * Gets the ihr current salary fixed.
	 *
	 * @return the ihr current salary fixed
	 */
	@Column(name = "ihr_current_salary_fixed")
	@Length(max = 15)
	public String getIhrCurrentSalaryFixed() {
		return this.ihrCurrentSalaryFixed;
	}

	/**
	 * Sets the ihr current salary fixed.
	 *
	 * @param ihrCurrentSalaryFixed the new ihr current salary fixed
	 */
	public void setIhrCurrentSalaryFixed(String ihrCurrentSalaryFixed) {
		this.ihrCurrentSalaryFixed = ihrCurrentSalaryFixed;
	}

	/**
	 * Gets the ihr current salary variable.
	 *
	 * @return the ihr current salary variable
	 */
	@Column(name = "ihr_current_salary_variable")
	@Length(max = 15)
	public String getIhrCurrentSalaryVariable() {
		return this.ihrCurrentSalaryVariable;
	}

	/**
	 * Sets the ihr current salary variable.
	 *
	 * @param ihrCurrentSalaryVariable the new ihr current salary variable
	 */
	public void setIhrCurrentSalaryVariable(String ihrCurrentSalaryVariable) {
		this.ihrCurrentSalaryVariable = ihrCurrentSalaryVariable;
	}

	/**
	 * Gets the ihr expected salary.
	 *
	 * @return the ihr expected salary
	 */
	@Column(name = "ihr_expected_salary", length = 250)
	@Length(max = 250)
	public String getIhrExpectedSalary() {
		return this.ihrExpectedSalary;
	}

	/**
	 * Sets the ihr expected salary.
	 *
	 * @param ihrExpectedSalary the new ihr expected salary
	 */
	public void setIhrExpectedSalary(String ihrExpectedSalary) {
		this.ihrExpectedSalary = ihrExpectedSalary;
	}

	/**
	 * Gets the ihr other expectation.
	 *
	 * @return the ihr other expectation
	 */
	@Column(name = "ihr_other_expectation", length = 250)
	@Length(max = 250)
	public String getIhrOtherExpectation() {
		return this.ihrOtherExpectation;
	}

	/**
	 * Sets the ihr other expectation.
	 *
	 * @param ihrOtherExpectation the new ihr other expectation
	 */
	public void setIhrOtherExpectation(String ihrOtherExpectation) {
		this.ihrOtherExpectation = ihrOtherExpectation;
	}

	/**
	 * Gets the ihr reason for change.
	 *
	 * @return the ihr reason for change
	 */
	@Column(name = "ihr_reason_for_change", length = 250)
	@Length(max = 250)
	public String getIhrReasonForChange() {
		return this.ihrReasonForChange;
	}

	/**
	 * Sets the ihr reason for change.
	 *
	 * @param ihrReasonForChange the new ihr reason for change
	 */
	public void setIhrReasonForChange(String ihrReasonForChange) {
		this.ihrReasonForChange = ihrReasonForChange;
	}

	/**
	 * Gets the ihr career plan3yrs.
	 *
	 * @return the ihr career plan3yrs
	 */
	@Column(name = "ihr_career_plan_3yrs", length = 45)
	@Length(max = 45)
	public String getIhrCareerPlan3yrs() {
		return this.ihrCareerPlan3yrs;
	}

	/**
	 * Sets the ihr career plan3yrs.
	 *
	 * @param ihrCareerPlan3yrs the new ihr career plan3yrs
	 */
	public void setIhrCareerPlan3yrs(String ihrCareerPlan3yrs) {
		this.ihrCareerPlan3yrs = ihrCareerPlan3yrs;
	}

	/**
	 * Gets the ihr career plan5yrs.
	 *
	 * @return the ihr career plan5yrs
	 */
	@Column(name = "ihr_career_plan_5yrs", length = 45)
	@Length(max = 45)
	public String getIhrCareerPlan5yrs() {
		return this.ihrCareerPlan5yrs;
	}

	/**
	 * Sets the ihr career plan5yrs.
	 *
	 * @param ihrCareerPlan5yrs the new ihr career plan5yrs
	 */
	public void setIhrCareerPlan5yrs(String ihrCareerPlan5yrs) {
		this.ihrCareerPlan5yrs = ihrCareerPlan5yrs;
	}

	/**
	 * Gets the ihr motivating factor.
	 *
	 * @return the ihr motivating factor
	 */
	@Column(name = "ihr_motivating_factor", length = 250)
	@Length(max = 250)
	public String getIhrMotivatingFactor() {
		return this.ihrMotivatingFactor;
	}

	/**
	 * Sets the ihr motivating factor.
	 *
	 * @param ihrMotivatingFactor the new ihr motivating factor
	 */
	public void setIhrMotivatingFactor(String ihrMotivatingFactor) {
		this.ihrMotivatingFactor = ihrMotivatingFactor;
	}

	/**
	 * Gets the ihr technical skill.
	 *
	 * @return the ihr technical skill
	 */
	@Column(name = "ihr_technical_skill", length = 250)
	@Length(max = 250)
	public String getIhrTechnicalSkill() {
		return this.ihrTechnicalSkill;
	}

	/**
	 * Sets the ihr technical skill.
	 *
	 * @param ihrTechnicalSkill the new ihr technical skill
	 */
	public void setIhrTechnicalSkill(String ihrTechnicalSkill) {
		this.ihrTechnicalSkill = ihrTechnicalSkill;
	}

	/**
	 * Gets the ihr offer in hand.
	 *
	 * @return the ihr offer in hand
	 */
	@Column(name = "ihr_offer_in_hand")
	public Boolean getIhrOfferInHand() {
		return this.ihrOfferInHand;
	}

	/**
	 * Sets the ihr offer in hand.
	 *
	 * @param ihrDetailOffer the new ihr offer in hand
	 */
	public void setIhrOfferInHand(Boolean ihrDetailOffer) {
		this.ihrOfferInHand = ihrDetailOffer;
	}

	/**
	 * Gets the ihr offer in hand detail.
	 *
	 * @return the ihr offer in hand detail
	 */
	@Column(name = "ihr_offer_in_hand_detail", length = 45)
	@Length(max = 45)
	public String getIhrOfferInHandDetail() {
		return this.ihrOfferInHandDetail;
	}

	/**
	 * Sets the ihr offer in hand detail.
	 *
	 * @param ihrOfferInHandDetail the new ihr offer in hand detail
	 */
	public void setIhrOfferInHandDetail(String ihrOfferInHandDetail) {
		this.ihrOfferInHandDetail = ihrOfferInHandDetail;
	}

	/**
	 * Gets the ihr location preference.
	 *
	 * @return the ihr location preference
	 */
	@Column(name = "ihr_location_preference", length = 15)
	@Length(max = 15)
	public String getIhrLocationPreference() {
		return this.ihrLocationPreference;
	}

	/**
	 * Sets the ihr location preference.
	 *
	 * @param ihrLocationPreference the new ihr location preference
	 */
	public void setIhrLocationPreference(String ihrLocationPreference) {
		this.ihrLocationPreference = ihrLocationPreference;
	}

	/**
	 * Gets the ihr current bond.
	 *
	 * @return the ihr current bond
	 */
	@Column(name = "ihr_current_bond")
	public Boolean getIhrCurrentBond() {
		return this.ihrCurrentBond;
	}

	/**
	 * Sets the ihr current bond.
	 *
	 * @param ihrCurrentBond the new ihr current bond
	 */
	public void setIhrCurrentBond(Boolean ihrCurrentBond) {
		this.ihrCurrentBond = ihrCurrentBond;
	}

	/**
	 * Gets the ihr current bond duration.
	 *
	 * @return the ihr current bond duration
	 */
	@Column(name = "ihr_current_bond_duration", length = 15)
	@Length(max = 15)
	public String getIhrCurrentBondDuration() {
		return this.ihrCurrentBondDuration;
	}

	/**
	 * Sets the ihr current bond duration.
	 *
	 * @param ihrCurrentBondDuration the new ihr current bond duration
	 */
	public void setIhrCurrentBondDuration(String ihrCurrentBondDuration) {
		this.ihrCurrentBondDuration = ihrCurrentBondDuration;
	}

	/**
	 * Gets the ihr current bond amount.
	 *
	 * @return the ihr current bond amount
	 */
	@Column(name = "ihr_current_bond_amount", length = 15)
	@Length(max = 15)
	public String getIhrCurrentBondAmount() {
		return this.ihrCurrentBondAmount;
	}

	/**
	 * Sets the ihr current bond amount.
	 *
	 * @param ihrCurrentBondAmount the new ihr current bond amount
	 */
	public void setIhrCurrentBondAmount(String ihrCurrentBondAmount) {
		this.ihrCurrentBondAmount = ihrCurrentBondAmount;
	}

	/**
	 * Gets the ihr contractual model.
	 *
	 * @return the ihr contractual model
	 */
	@Column(name = "ihr_contractual_model")
	public Boolean getIhrContractualModel() {
		return this.ihrContractualModel;
	}

	/**
	 * Sets the ihr contractual model.
	 *
	 * @param ihrContractualModel the new ihr contractual model
	 */
	public void setIhrContractualModel(Boolean ihrContractualModel) {
		this.ihrContractualModel = ihrContractualModel;
	}

	/**
	 * Gets the ihr notice period days.
	 *
	 * @return the ihr notice period days
	 */
	@Column(name = "ihr_notice_period_days")
	public Integer getIhrNoticePeriodDays() {
		return this.ihrNoticePeriodDays;
	}

	/**
	 * Sets the ihr notice period days.
	 *
	 * @param ihrNoticePeriodDays the new ihr notice period days
	 */
	public void setIhrNoticePeriodDays(Integer ihrNoticePeriodDays) {
		this.ihrNoticePeriodDays = ihrNoticePeriodDays;
	}

	/**
	 * Gets the ihr notice period date.
	 *
	 * @return the ihr notice period date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ihr_notice_period_date", length = 0)
	public Date getIhrNoticePeriodDate() {
		return this.ihrNoticePeriodDate;
	}

	/**
	 * Sets the ihr notice period date.
	 *
	 * @param ihrNoticePeriodDate the new ihr notice period date
	 */
	public void setIhrNoticePeriodDate(Date ihrNoticePeriodDate) {
		this.ihrNoticePeriodDate = ihrNoticePeriodDate;
	}

	/**
	 * Gets the ihr passport detail.
	 *
	 * @return the ihr passport detail
	 */
	@Column(name = "ihr_passport_detail", length = 250)
	@Length(max = 250)
	public String getIhrPassportDetail() {
		return this.ihrPassportDetail;
	}

	/**
	 * Sets the ihr passport detail.
	 *
	 * @param ihrPassportDetail the new ihr passport detail
	 */
	public void setIhrPassportDetail(String ihrPassportDetail) {
		this.ihrPassportDetail = ihrPassportDetail;
	}

	/**
	 * Gets the ihr application form.
	 *
	 * @return the ihr application form
	 */
	@Column(name = "ihr_application_form", length = 15)
	@Length(max = 15)
	public String getIhrApplicationForm() {
		return this.ihrApplicationForm;
	}

	/**
	 * Sets the ihr application form.
	 *
	 * @param ihrApplicationForm the new ihr application form
	 */
	public void setIhrApplicationForm(String ihrApplicationForm) {
		this.ihrApplicationForm = ihrApplicationForm;
	}

	/**
	 * Gets the ihr recommended.
	 *
	 * @return the ihr recommended
	 */
	@Column(name = "ihr_recommended", length = 15)
	@Length(max = 15)
	public String getIhrRecommended() {
		return this.ihrRecommended;
	}
	
	/**
	 * Hr status.
	 *
	 * @return the string
	 */
	@Transient
	public String hrStatus() {
		String result = RTSConstants.FAIL;
		if (this.ihrRecommended != null
				&& (this.ihrRecommended.equalsIgnoreCase("Yes") || this.ihrRecommended
						.equalsIgnoreCase("Contract Hiring"))) {
			result = RTSConstants.PASSED;
		}

		return result;
	}

	/**
	 * Sets the ihr recommended.
	 *
	 * @param ihrRecommended the new ihr recommended
	 */
	public void setIhrRecommended(String ihrRecommended) {
		this.ihrRecommended = ihrRecommended;
	}

	/**
	 * Gets the ihr father.
	 *
	 * @return the ihr father
	 */
	@Column(name = "ihr_father", length = 45)
	@Length(max = 45)
	public String getIhrFather() {
		return this.ihrFather;
	}

	/**
	 * Sets the ihr father.
	 *
	 * @param ihrFather the new ihr father
	 */
	public void setIhrFather(String ihrFather) {
		this.ihrFather = ihrFather;
	}

	/**
	 * Gets the ihr mother.
	 *
	 * @return the ihr mother
	 */
	@Column(name = "ihr_mother", length = 45)
	@Length(max = 45)
	public String getIhrMother() {
		return this.ihrMother;
	}

	/**
	 * Sets the ihr mother.
	 *
	 * @param ihrMother the new ihr mother
	 */
	public void setIhrMother(String ihrMother) {
		this.ihrMother = ihrMother;
	}

	/**
	 * Gets the ihr spouse.
	 *
	 * @return the ihr spouse
	 */
	@Column(name = "ihr_spouse", length = 45)
	@Length(max = 45)
	public String getIhrSpouse() {
		return this.ihrSpouse;
	}

	/**
	 * Sets the ihr spouse.
	 *
	 * @param ihrSpouse the new ihr spouse
	 */
	public void setIhrSpouse(String ihrSpouse) {
		this.ihrSpouse = ihrSpouse;
	}

	/**
	 * Gets the ihr children.
	 *
	 * @return the ihr children
	 */
	@Column(name = "ihr_children", length = 45)
	@Length(max = 45)
	public String getIhrChildren() {
		return this.ihrChildren;
	}

	/**
	 * Sets the ihr children.
	 *
	 * @param ihrChildren the new ihr children
	 */
	public void setIhrChildren(String ihrChildren) {
		this.ihrChildren = ihrChildren;
	}

	/**
	 * Gets the ihr sibling.
	 *
	 * @return the ihr sibling
	 */
	@Column(name = "ihr_sibling", length = 45)
	@Length(max = 45)
	public String getIhrSibling() {
		return this.ihrSibling;
	}

	/**
	 * Sets the ihr sibling.
	 *
	 * @param ihrSibling the new ihr sibling
	 */
	public void setIhrSibling(String ihrSibling) {
		this.ihrSibling = ihrSibling;
	}

	/**
	 * Gets the ihr comment.
	 *
	 * @return the ihr comment
	 */
	@Column(name = "ihr_comment", length = 250)
	@Length(max = 250)
	public String getIhrComment() {
		return this.ihrComment;
	}

	/**
	 * Sets the ihr comment.
	 *
	 * @param ihrComment the new ihr comment
	 */
	public void setIhrComment(String ihrComment) {
		this.ihrComment = ihrComment;
	}
	
	/**
	 * Gets the interview schedule.
	 *
	 * @return the interview schedule
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ihr_its_interview_schedule_id")
	public InterviewSchedule getInterviewSchedule() {
		return interviewSchedule;
	}

	/**
	 * Sets the interview schedule.
	 *
	 * @param interviewSchedule the new interview schedule
	 */
	public void setInterviewSchedule(InterviewSchedule interviewSchedule) {
		this.interviewSchedule = interviewSchedule;
	}

	/**
	 * Gets the ihrforeign language know.
	 *
	 * @return the ihrforeign language know
	 */
	@Column(name = "ihr_foreign_language_know", length = 50)
	@Length(max = 50)
	public String getIhrforeignLanguageKnow() {
		return ihrforeignLanguageKnow;
	}

	/**
	 * Sets the ihrforeign language know.
	 *
	 * @param ihrforeignLanguageKnow the new ihrforeign language know
	 */
	public void setIhrforeignLanguageKnow(String ihrforeignLanguageKnow) {
		this.ihrforeignLanguageKnow = ihrforeignLanguageKnow;
	}
}
