package model;

// Generated Apr 26, 2014 11:46:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DimStudents generated by hbm2java
 */
@Entity
@Table(name = "DimStudents", schema = "dbo", catalog = "RDW")
public class DimStudents implements java.io.Serializable {

	private long stuId;
	private String studentId;
	private String firstName;
	private String lastName;
	private Date birthDay;
	private int gender;
	private String emailAdress;
	private int academicYear;
	private Set<FactStudentGrades> factStudentGradeses = new HashSet<FactStudentGrades>(
			0);

	public DimStudents() {
	}

	public DimStudents(final long stuId, final String studentId,
			final String firstName, final String lastName, final Date birthDay,
			final int gender, final String emailAdress, final int academicYear) {
		this.stuId = stuId;
		this.studentId = studentId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDay = birthDay;
		this.gender = gender;
		this.emailAdress = emailAdress;
		this.academicYear = academicYear;
	}

	public DimStudents(final long stuId, final String studentId,
			final String firstName, final String lastName, final Date birthDay,
			final int gender, final String emailAdress, final int academicYear,
			final Set<FactStudentGrades> factStudentGradeses) {
		this.stuId = stuId;
		this.studentId = studentId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDay = birthDay;
		this.gender = gender;
		this.emailAdress = emailAdress;
		this.academicYear = academicYear;
		this.factStudentGradeses = factStudentGradeses;
	}

	@Id
	@Column(name = "stu_id", unique = true, nullable = false)
	public long getStuId() {
		return this.stuId;
	}

	public void setStuId(final long stuId) {
		this.stuId = stuId;
	}

	@Column(name = "studentId", nullable = false)
	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(final String studentId) {
		this.studentId = studentId;
	}

	@Column(name = "firstName", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(final String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(final String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "birthDay", nullable = false, length = 23)
	public Date getBirthDay() {
		return this.birthDay;
	}

	public void setBirthDay(final Date birthDay) {
		this.birthDay = birthDay;
	}

	@Column(name = "gender", nullable = false)
	public int getGender() {
		return this.gender;
	}

	public void setGender(final int gender) {
		this.gender = gender;
	}

	@Column(name = "emailAdress", nullable = false)
	public String getEmailAdress() {
		return this.emailAdress;
	}

	public void setEmailAdress(final String emailAdress) {
		this.emailAdress = emailAdress;
	}

	@Column(name = "academicYear", nullable = false)
	public int getAcademicYear() {
		return this.academicYear;
	}

	public void setAcademicYear(final int academicYear) {
		this.academicYear = academicYear;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimStudents")
	public Set<FactStudentGrades> getFactStudentGradeses() {
		return this.factStudentGradeses;
	}

	public void setFactStudentGradeses(
			final Set<FactStudentGrades> factStudentGradeses) {
		this.factStudentGradeses = factStudentGradeses;
	}

}
