package model;

// Generated Apr 26, 2014 11:46:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DimSubjectGroups generated by hbm2java
 */
@Entity
@Table(name = "DimSubjectGroups", schema = "dbo", catalog = "RDW")
public class DimSubjectGroups implements java.io.Serializable {

	private long subgrpId;
	private Long subjectGroupId;
	private String subjectGroupName;
	private Set<DimSubjects> dimSubjectses = new HashSet<DimSubjects>(0);

	public DimSubjectGroups() {
	}

	public DimSubjectGroups(final long subgrpId) {
		this.subgrpId = subgrpId;
	}

	public DimSubjectGroups(final long subgrpId, final Long subjectGroupId,
			final String subjectGroupName, final Set<DimSubjects> dimSubjectses) {
		this.subgrpId = subgrpId;
		this.subjectGroupId = subjectGroupId;
		this.subjectGroupName = subjectGroupName;
		this.dimSubjectses = dimSubjectses;
	}

	@Id
	@Column(name = "subgrpId", unique = true, nullable = false)
	public long getSubgrpId() {
		return this.subgrpId;
	}

	public void setSubgrpId(final long subgrpId) {
		this.subgrpId = subgrpId;
	}

	@Column(name = "subjectGroupId")
	public Long getSubjectGroupId() {
		return this.subjectGroupId;
	}

	public void setSubjectGroupId(final Long subjectGroupId) {
		this.subjectGroupId = subjectGroupId;
	}

	@Column(name = "subjectGroupName")
	public String getSubjectGroupName() {
		return this.subjectGroupName;
	}

	public void setSubjectGroupName(final String subjectGroupName) {
		this.subjectGroupName = subjectGroupName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimSubjectGroups")
	public Set<DimSubjects> getDimSubjectses() {
		return this.dimSubjectses;
	}

	public void setDimSubjectses(final Set<DimSubjects> dimSubjectses) {
		this.dimSubjectses = dimSubjectses;
	}

}
