package model;

// Generated Apr 26, 2014 11:46:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DimSubjects generated by hbm2java
 */
@Entity
@Table(name = "DimSubjects", schema = "dbo", catalog = "RDW")
public class DimSubjects implements java.io.Serializable {

	private int subId;
	private DimSubjectGroups dimSubjectGroups;
	private String subjectId;
	private String subjectName;
	private Set<FactStudentGrades> factStudentGradeses = new HashSet<FactStudentGrades>(
			0);

	public DimSubjects() {
	}

	public DimSubjects(final int subId, final String subjectId,
			final String subjectName) {
		this.subId = subId;
		this.subjectId = subjectId;
		this.subjectName = subjectName;
	}

	public DimSubjects(final int subId, final DimSubjectGroups dimSubjectGroups,
			final String subjectId, final String subjectName,
			final Set<FactStudentGrades> factStudentGradeses) {
		this.subId = subId;
		this.dimSubjectGroups = dimSubjectGroups;
		this.subjectId = subjectId;
		this.subjectName = subjectName;
		this.factStudentGradeses = factStudentGradeses;
	}

	@Id
	@Column(name = "sub_id", unique = true, nullable = false)
	public int getSubId() {
		return this.subId;
	}

	public void setSubId(final int subId) {
		this.subId = subId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subgrpId")
	public DimSubjectGroups getDimSubjectGroups() {
		return this.dimSubjectGroups;
	}

	public void setDimSubjectGroups(final DimSubjectGroups dimSubjectGroups) {
		this.dimSubjectGroups = dimSubjectGroups;
	}

	@Column(name = "subjectId", nullable = false)
	public String getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(final String subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "subjectName", nullable = false)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(final String subjectName) {
		this.subjectName = subjectName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimSubjects")
	public Set<FactStudentGrades> getFactStudentGradeses() {
		return this.factStudentGradeses;
	}

	public void setFactStudentGradeses(
			final Set<FactStudentGrades> factStudentGradeses) {
		this.factStudentGradeses = factStudentGradeses;
	}

}
