package model;

// Generated Apr 26, 2014 11:46:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FactStudentGrades generated by hbm2java
 */
@Entity
@Table(name = "FactStudentGrades", schema = "dbo", catalog = "RDW")
public class FactStudentGrades implements java.io.Serializable {

	private FactStudentGradesId id;
	private DimSubjects dimSubjects;
	private DimTimes dimTimes;
	private DimStudents dimStudents;
	private Double assignmentGrade;
	private Double midtermGrade;
	private Double finalGrade;
	private Double summarizedGrade;
	private String assignmentGradeLetter;
	private String midtermGradeLetter;
	private String finalGradeLetter;
	private String summarizedGradeLetter;
	private String gradeEval;

	public FactStudentGrades() {
	}

	public FactStudentGrades(final FactStudentGradesId id, final DimSubjects dimSubjects,
			final DimTimes dimTimes, final DimStudents dimStudents) {
		this.id = id;
		this.dimSubjects = dimSubjects;
		this.dimTimes = dimTimes;
		this.dimStudents = dimStudents;
	}

	public FactStudentGrades(final FactStudentGradesId id, final DimSubjects dimSubjects,
			final DimTimes dimTimes, final DimStudents dimStudents, final Double assignmentGrade,
			final Double midtermGrade, final Double finalGrade, final Double summarizedGrade,
			final String assignmentGradeLetter,
			final String midtermGradeLetter, final String finalGradeLetter,
			final String summarizedGradeLetter, final String gradeEval) {
		this.id = id;
		this.dimSubjects = dimSubjects;
		this.dimTimes = dimTimes;
		this.dimStudents = dimStudents;
		this.assignmentGrade = assignmentGrade;
		this.midtermGrade = midtermGrade;
		this.finalGrade = finalGrade;
		this.summarizedGrade = summarizedGrade;
		this.assignmentGradeLetter = assignmentGradeLetter;
		this.midtermGradeLetter = midtermGradeLetter;
		this.finalGradeLetter = finalGradeLetter;
		this.summarizedGradeLetter = summarizedGradeLetter;
		this.gradeEval = gradeEval;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "studentId", column = @Column(name = "studentId", nullable = false)),
			@AttributeOverride(name = "subjectId", column = @Column(name = "subjectId", nullable = false)),
			@AttributeOverride(name = "timeId", column = @Column(name = "time_id", nullable = false)) })
	public FactStudentGradesId getId() {
		return this.id;
	}

	public void setId(final FactStudentGradesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subjectId", nullable = false, insertable = false, updatable = false)
	public DimSubjects getDimSubjects() {
		return this.dimSubjects;
	}

	public void setDimSubjects(final DimSubjects dimSubjects) {
		this.dimSubjects = dimSubjects;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "time_id", nullable = false, insertable = false, updatable = false)
	public DimTimes getDimTimes() {
		return this.dimTimes;
	}

	public void setDimTimes(final DimTimes dimTimes) {
		this.dimTimes = dimTimes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "studentId", nullable = false, insertable = false, updatable = false)
	public DimStudents getDimStudents() {
		return this.dimStudents;
	}

	public void setDimStudents(final DimStudents dimStudents) {
		this.dimStudents = dimStudents;
	}

	@Column(name = "assignmentGrade", precision = 53, scale = 0)
	public Double getAssignmentGrade() {
		return this.assignmentGrade;
	}

	public void setAssignmentGrade(final Double assignmentGrade) {
		this.assignmentGrade = assignmentGrade;
	}

	@Column(name = "midtermGrade", precision = 53, scale = 0)
	public Double getMidtermGrade() {
		return this.midtermGrade;
	}

	public void setMidtermGrade(final Double midtermGrade) {
		this.midtermGrade = midtermGrade;
	}

	@Column(name = "finalGrade", precision = 53, scale = 0)
	public Double getFinalGrade() {
		return this.finalGrade;
	}

	public void setFinalGrade(final Double finalGrade) {
		this.finalGrade = finalGrade;
	}

	@Column(name = "summarizedGrade", precision = 53, scale = 0)
	public Double getSummarizedGrade() {
		return this.summarizedGrade;
	}

	public void setSummarizedGrade(final Double summarizedGrade) {
		this.summarizedGrade = summarizedGrade;
	}

	@Column(name = "assignmentGradeLetter")
	public String getAssignmentGradeLetter() {
		return this.assignmentGradeLetter;
	}

	public void setAssignmentGradeLetter(final String assignmentGradeLetter) {
		this.assignmentGradeLetter = assignmentGradeLetter;
	}

	@Column(name = "midtermGradeLetter")
	public String getMidtermGradeLetter() {
		return this.midtermGradeLetter;
	}

	public void setMidtermGradeLetter(final String midtermGradeLetter) {
		this.midtermGradeLetter = midtermGradeLetter;
	}

	@Column(name = "finalGradeLetter")
	public String getFinalGradeLetter() {
		return this.finalGradeLetter;
	}

	public void setFinalGradeLetter(final String finalGradeLetter) {
		this.finalGradeLetter = finalGradeLetter;
	}

	@Column(name = "summarizedGradeLetter")
	public String getSummarizedGradeLetter() {
		return this.summarizedGradeLetter;
	}

	public void setSummarizedGradeLetter(final String summarizedGradeLetter) {
		this.summarizedGradeLetter = summarizedGradeLetter;
	}

	@Column(name = "gradeEval")
	public String getGradeEval() {
		return this.gradeEval;
	}

	public void setGradeEval(final String gradeEval) {
		this.gradeEval = gradeEval;
	}

}
