package model;

// Generated Apr 26, 2014 11:46:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FactStudentGradesId generated by hbm2java
 */
@Embeddable
public class FactStudentGradesId implements java.io.Serializable {

	private long studentId;
	private int subjectId;
	private int timeId;

	public FactStudentGradesId() {
	}

	public FactStudentGradesId(long studentId, int subjectId, int timeId) {
		this.studentId = studentId;
		this.subjectId = subjectId;
		this.timeId = timeId;
	}

	@Column(name = "studentId", nullable = false)
	public long getStudentId() {
		return this.studentId;
	}

	public void setStudentId(long studentId) {
		this.studentId = studentId;
	}

	@Column(name = "subjectId", nullable = false)
	public int getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(int subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "time_id", nullable = false)
	public int getTimeId() {
		return this.timeId;
	}

	public void setTimeId(int timeId) {
		this.timeId = timeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FactStudentGradesId))
			return false;
		FactStudentGradesId castOther = (FactStudentGradesId) other;

		return (this.getStudentId() == castOther.getStudentId())
				&& (this.getSubjectId() == castOther.getSubjectId())
				&& (this.getTimeId() == castOther.getTimeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getStudentId();
		result = 37 * result + this.getSubjectId();
		result = 37 * result + this.getTimeId();
		return result;
	}

}
